### ISSUE TITLE
Subtitles on Reviewed Books

### ISSUE THREAD

**Issue by SClarkWT** [dcpurton/biblatex-sbl#10]
Right now it still prints the full title of a reviewed book:

> <sup>29</sup> Urban C. von Wahlde, review of *The Quest for the Origin of John’s Gospel: A Source-Oriented Approach*, by Thomas L. Brodie, CBQ 56 (1994): 582–83.

Subsequent citation:  
> <sup>30</sup> Wahlde, review of *The Quest for the Origin of John’s Gospel: A Source-Oriented Approach*, (by Brodie), 2.

When I think it should be

> <sup>30</sup> Wahlde, review of *The Quest for the Origin of John’s Gospel*, (by Brodie), 2

Maybe implement a ```revdsubtitle``` field?

**Comment by Nhapsie** [comment]
There should be a field for subsequent reviewed references, like "shortrevdtitle" but I guess it's not active. David could implement that for us.

**Comment by dcpurton** [comment]
Try now. I added support for revdshorttitle and fixed the problem with revdsubtitle.

**Comment by SClarkWT** [comment]
Looks good, thanks!

**Comment by Nhapsie** [comment]
For some reason latest git is not fixing this.

**Comment by dcpurton** [comment]
@Nhapsie, It is working for me. Check this MWE. What do you have to change to make it fail?

```
\documentclass{article}

\usepackage[style=sbl,backend=biber,ibidtracker=false]{biblatex}
\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@review{wahlde:1994,
  author = {von Wahlde, Urban C.},
  revdtitle = {The Quest for the Origin of John's Gospel: A Source-Oriented Approach},
  revdshorttitle = {The Quest for the Origin of John's Gospel},
  revdauthor = {Brodie, Thomas L.},
  journaltitle = {Catholic Biblical Quarterly},
  shortjournal = {CBQ},
  volume = {56},
  date = {1994},
  pages = {582-583}
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\cite{wahlde:1994}

\cite{wahlde:1994}

\printbiblist{abbreviations}

\printbibliography
\end{document} 
```

This is the output I get:

![revdshorttitle](https://cloud.githubusercontent.com/assets/6268044/12380814/a74f8f86-bdcb-11e5-9930-12bf110887d3.png)

**Comment by Nhapsie** [comment]
my terminal continues to input the problem:
![screen shot 2016-01-17 at 6 01 27 pm](https://cloud.githubusercontent.com/assets/5918656/12380934/98366ba0-bd44-11e5-8df8-2d6950f7ddcc.png)

**Comment by SClarkWT** [comment]
Any reason the extra spaces may be justification? But I see what you're saying about the second citation.

**Comment by Nhapsie** [comment]
Updated biblatex to 3.0 and biber to 2.3, no luck yet. The only biber type I could not install is x86_64-cygwin, don't know if it's playing a role. I will keep an eye on this problem...

**Comment by dcpurton** [comment]
@Nhapsie, check out the latest revision and add `\listfiles` to the top of the MWE then post the output when you compile it. I just updated the version string to v0.2. make sure biblatex-sbl.def, sbl.bbx, sbl.cbx, and sbl-english.ldx have the version string `2016/01/18 v0.2`.

I notice that there are no pages specified in your second citation which is also different to my output.

**Comment by dcpurton** [comment]
The larger space after the colon is a feature of LaTeX. Different punctuation allows different stretch of space after it. So after a period a larger space is allowed than after colons and semi-colons which allow a larger space than a normal space.

If you ant to disable this behaviour, put `\frenchspacing` somewhere in your preamble.

@SClarkWT is right that justification also affects this. This is why sometimes it looks like a small amount of space.

**Comment by Nhapsie** [comment]
I didn't even finish making all these suggestions, and I got a positive result. Order has been restored in Latexland. Thanks David and SClark.
![screen shot 2016-01-17 at 10 33 18 pm](https://cloud.githubusercontent.com/assets/5918656/12383376/057c28f0-bd6b-11e5-894b-38febbb05b12.png)

**Comment by dcpurton** [comment]
Great!
