### ISSUE TITLE
Typo \ifool -> \ifbool

### ISSUE THREAD

**Issue by moewew** [dcpurton/biblatex-sbl#109]
Via https://tex.stackexchange.com/q/505821/35864

there is a typo in

https://github.com/dcpurton/biblatex-sbl/blob/86164470c305bca059ae23a7a1e83066bf5402cc/latex/biblatex-sbl.def#L130

it should probably be

```latex
\ifbool{bbx@inset}
```

MWE to reproduce an 
```
! Undefined control sequence.
<argument> \ifool 
```

```latex
\documentclass{article}
\usepackage[style=sbl, citepages=separate]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
\autocite[380]{geer}

\printbibliography
\end{document}
```

**Comment by dcpurton** [comment]
Thanks! This is because the '' key on my keyoard does not work well…
