### ISSUE TITLE
Separation of bib style and format?

### ISSUE THREAD

**Issue by folofjc** [dcpurton/biblatex-sbl#113]
This will be long, but the basic question is this: if I just need the bibliography and citation _styles_ for certain entry types, but not the whole SBL formatting, can I just grab the relevant files from this repo?

The long version: I really appreciate this package and used it for a paper I was writing to submit to a journal that used this style. However, for my dissertation, my school uses the Chicago manual and Turabian for the paper formatting, bibliography and footnote styles, etc. I tried to get everything to work with `biblatex-sbl` but I couldn't get it. I have been using `biblcatex-chicago` because it is 95% of the way there and only required very minor tweaks. Also, everything I have uses polyglossia and xelatex, and based upon previous issues that you helped me with, and the current documentation, you recommend babel and lualatex.

However, as far as the style of citations, there are definitely things in `biblatex-sbl` that I like (church fathers, lexicons, etc) that `biblatex-chicago` does not have.

To start off with, it is not self-evident to me that switching to lua and babel is less work than implementing the few bib styles that I need with `biblatex-chicago`. I have tried switching to babel and lua, and it was not easy or clean. Maybe it is not a good reason, but I _like_ `xelatex`. So I know that all of this is my problem and I totally understand if it is too much effort to give an answer.

I have been looking at [this tex.se answer for adding types](https://tex.stackexchange.com/questions/175776/how-can-i-create-entirely-new-data-types-with-biblatex-biber) and [this tex.se answer for inheritance](https://tex.stackexchange.com/questions/169505/biblatex-inherit-shorthand), both by @moewew for help. Is there an easy way to include these extra entry types and their formatting independently from the entire SBL format?

One day I might make a package for formatting due to our style requirements, and would be helpful if I could pull from `biblatex-sbl` in some way.

**Comment by folofjc** [comment]
Full disclosure: I asked [this question on tex.se](https://tex.stackexchange.com/questions/582442/incollection-with-biblatex-chicago-shorthand-collection-not-showing-author-or-ti) without mentioning `biblatex-sbl` to see if there was an easy way to do it a different way.

**Comment by dcpurton** [comment]
@folofjc The SBL styles are pretty tightly integrated together, especially when it comes to the more special use cases. It would be practically impossible to pull out a particular entry type. What you could do though is use similar methods to what I have done and implement something yourself. Although `biblatex-chicago` is a very complex style and not easy to modify…

BTW you may be interested to note that SBL has changed their style for both lexicons and church fathers (as well as a bunch of other things). See all the updates at https://sblhs2.com/. I've started rewriting `biblatex-sbl` to incorporate these changes. But it's not ready yet, especially when it comes to the more specialised examples.

`xelatex` is now much more of a possibility since improvements in `polyglossia` have solved the issues with `biblatex`. I still find `polyglossia` with `bidi` for Hebrew and other RTL languages not as good though. But it should be good enough for a few words and phrases here and there.

I'll have a look at your txs question and see if there is an easy hack.

**Comment by folofjc** [comment]
@dcpurton okay thanks! Yeah, I do a lot in Hebrew and have found polyglossia to work okay for my needs. But I usually only need a few words or a few verses, nothing super specialized. That is probably why it hasn't bit me yet.

Yeah, I noticed that `biblatex-chicago` is hard to modify, but I think you are right that I will just have to implement something similar to what you have done. If it is too much work I will try to switch to `biblatex-sbl` again and see if I can get the formatting to match again.

Thanks again for your help!

**Comment by dcpurton** [comment]
@folofjc I offer a very hacky (but also very easy) solution to your tsx question.

**Comment by folofjc** [comment]
@dcpurton Thanks so much! You are right, that is super easy. I could probably do that for ANF, NPNF, etc, as well. I really hate that our style guide is so hack-y that they can't just say "use SBL" and be done with it. 

Also, thanks for the heads up on the SBLHS2 changes. I read through their blog posts. That is interesting, I have never seen anyone cite BDAG, HALOT, LEH, etc in this way; always with a page number. But I think I can use the `inreference` for this, since it does the "s.v." but I will have to double check everything. Looks like `inreference` in `biblatex-chicago` requires a .bib entry for each item in the dictionary for the `lista` field. Ugh. 

I really appreciate your help! Feel free to close this issue

**Comment by dcpurton** [comment]
Yes, I also have never seen lexicons referenced in this way in actual books. Although I don't really operate in the academic world, so assumed that I just read the wrong books… For my new version of `biblatex-sbl` I'm requiring the s.v. to be put into the postnote (it's not automatic).

Some of their changes make good sense and result in more consistency. But there's plenty of things I'm still puzzled by when it comes to referencing ancient texts. Unfortunately I'm not really familiar with most of them, and the style guide and posts are not written for someone like me who is trying to produce computer rules. Judging by the number of errors in the SBLHS, they aren't using a computer to do their referencing either ;).

**Comment by folofjc** [comment]
Haha well I am quite familiar with most of the reference works in the blog posts (at least the first 7). There are a few I have never worked with (the Cambridge stuff in 9 and 10). For ancient texts, I only ever use critical editions, never anything unpublished. 

Its funny, the guy from twitter asking about PG is a friend of mine. I also don't like how they changed the superscript for NPNF.

But if I can help in anyway or you want me to look something up, just let me know! 

Well I really appreciate you helping those of us trying straddle between the two worlds (though I admit I do so poorly).

**Comment by folofjc** [comment]
@dcpurton I realized after reading the blog posts that you pointed me to, that what I had in my MWE on tex.se was wrong. I left a comment and updated the MWE, but I fear at this point it is too complicated for a simple macro.
