### ISSUE TITLE
Page numbers incorrect for multiple of 100

### ISSUE THREAD

**Issue by folofjc** [dcpurton/biblatex-sbl#114]
The SBLHS2 states in 4.2.4 on page 20 that when giving a range of numbers, if the first number begins with 100, then the second number should include all digits (from CMOS17 9.61). However, I noticed that in the `biblatex-sbl-examples.pdf` on page 34, the `doomedprince` entry only shows 200-3, which is incorrect. I can reproduce with the following MWE:
```
\documentclass[letterpaper,12pt]{report}
\usepackage[english=american]{csquotes}

\usepackage[style=sbl]{biblatex}

\begin{filecontents}[overwrite]{temp.bib}
   @mvbook{AEL,
      author = {Lichtheim, Miriam},
      title = {Ancient Egyptian Literature},
      shorttitle = {AEL},
      volumes = {3},
      location = {Berkeley},
      publisher = {University of California Press},
      date = {1971/1980},
      shorthand = {AEL},
      options = {skipbib}
   }
   @book{lichtheim:1976,
      author = {Lichtheim, Miriam},
      title = {Ancient Egyptian Literature},
      shorttitle = {AEL},
      volume = {2},
      location = {Berkeley},
      publisher = {University of California Press},
      date = {1976},
      shorthand = {AEL},
      xref = {AEL},
      options = {skipbiblist}
   }
   @ancienttext{doomedprince,
      title = {The Doomed Prince},
      pages = {200-203},
      related = {lichtheim:1976},
      relatedoptions = {shorthand=short,usevolume=false,skipbiblist}
   }
\end{filecontents}

\addbibresource{temp.bib}
\begin{document}
\null\vfill
Test.\autocite{doomedprince}
\clearpage
\printbibliography
\end{document}
```

Which gives:
![Screenshot from 2021-02-11 08-31-12](https://user-images.githubusercontent.com/4741202/107611149-9c8c9680-6c43-11eb-983b-77335ed08142.png)

The `2:200-3` should read `2:200-203`.

**Comment by dcpurton** [comment]
Nice pick up! I had missed that part of the handbook and was just confused about what was going on. I think I'd noticed the part about numbering and ancient works somewhere on the blog.

I'll see if I can find a way of doing this. Perhaps `biblatex-chicago` handles it.

**Comment by dcpurton** [comment]
Hmmm. For the record neither `biblatex-chicago` not `windy` city seem to compress page ranges at all. You have to do it yourself.

**Comment by folofjc** [comment]
Yep, I do all the page ranges myself in the bib entries for `biblatex-chicago`. 

I just found `windycity` the other day. I have not looked into it but am kind of surprised that there is a _second_ chicago style for `biblatex`...

**Comment by dcpurton** [comment]
Disabling automatic page compression (which actually fails at a few points) is not hard and I suggest you do that for now:

Add this to your preamble:

```TeX
\DeclareFieldFormat{volcitepages}{\mknormrange{#1}}
\DeclareFieldFormat{postnote}{%
  \iffieldundef{eid}
    {\mknormrange{#1}}
    {\mkpageprefix[pagination][\mknormrange]{#1}}}
\DeclareFieldFormat{pages}{\mknormrange{#1}}
\DeclareFieldFormat{pagepages}{\mkpageprefix[pagination][\mknormrange]{#1}}
\DeclareFieldFormat{pagesin}{\mkpageprefix[pagination][\mknormrange]{#1} \usebibmacro{in}}
\DeclareFieldFormat{altpostnote}{\mknormrange{#1}}
```

**Comment by dcpurton** [comment]
Oh forget that.

Just add

```TeX
\setcounter{maxcomprange}{10}
\DeclareFieldFormat{altpostnote}{\mknormrange{#1}}
```

(Leave the `altpostnote` as `\mknormrange` as this is mainly used for sections or parts of ancient works.)

This gives:

```TeX
\documentclass{article}

\usepackage[style=sbl]{biblatex}

\setcounter{maxcomprange}{10}

\begin{document}

3–9, 11–17, 53–55, 94–113

100–103, 500–508, 502–8, 1100–1187

285–89, 306–23, 809–902, 1003–7

327–35, 448–503, 1465–89, 1698–1703

\medskip

\mkcomprange{3-9, 11-17, 53-55, 94-113}

\mkcomprange{100-103, 500-508, 502–8, 1100-1187}

\mkcomprange{285-89, 306-23, 809-902, 1003-7}

\mkcomprange{327-35, 448-503, 1465-89, 1698-1703}

\end{document}
```

![tex226](https://user-images.githubusercontent.com/6268044/107634191-114de800-6cb9-11eb-9c83-edbae4832bef.png)

**Comment by dcpurton** [comment]
@folofjc , What's the logic for 1698–1703?

**Comment by folofjc** [comment]
1698-703.

It's not that intuitive, but for anything three digits or more, where the last two digits of the first number are not between 00-09, you only show the digits that changed BUT at least two digits: 150-51, 1698-99, 1698-701, 1998-2003

For three digits or more where the last two digits of the first number are 00 (multiples of 100): In this case, you show everything. So 1200-1203, 300-301, etc.

For three digits or more, where the last two digits of the first number are between 01-09, you only show the digits that changed (no requirement on the minimum of two, because then you could have a leading zero, which would look weird). So 1601-3, 1601-11, 509-602, etc.

**Comment by folofjc** [comment]
The table in CMOS17 9.61 is pretty helpful, I think.

**Comment by dcpurton** [comment]
@folofjc hmm. That doesn't quite match SBLHS2 in §4.2.4 (top of page 20), which lists 1698–1703. Which is why I wondered about it as this doesn't seem obvious to me :).

Any thoughts?

(I don't have a copy or subscription of CMOS)

**Comment by folofjc** [comment]
Wow, you are right. They _say_ that they follow CMOS, but there is an example in CMOS17 that directly contradicts this: it gives the example of: 1496-500. I don't have CMOS16 (which is what SBLHS2 had at the time of its printing), but the text in CMOS17 says that this table has remained unchanged since the beginning.

My guess is this is another error in SBLHS2. It is up to you if you want to follow the text, or the intent ;) I sent the SBLHS people an email, I'll let you know what they say (if they respond).

**Comment by dcpurton** [comment]
OK. Here's some code that I think implements what you've said for CMOS (which makes more sense to me).

Just add the preamble into your document and see if you can break it:

```TeX
\documentclass{article}
\pagestyle{empty}
\parindent=0pt

\usepackage[style=sbl]{biblatex}

%\setcounter{maxcomprange}{100}% SBLHS2 §4.2.4 ??

\makeatletter
\def\blx@comprange@check#1#2{%
  \blx@imc@ifinteger{#1}
    {\blx@imc@ifinteger{#2}
       {\@firstoftwo}
       {\@secondoftwo}}
    {\@secondoftwo}
    {\blx@tempcnta=#1
     \divide\blx@tempcnta by 100
     \multiply\blx@tempcnta by 100
     \multiply\blx@tempcnta by -1
     \advance\blx@tempcnta by #1\relax
     \ifnum\blx@tempcnta=0
       \blx@normrange@process{#1}{#2}%
     \else
       \blx@comprange@comp{#1}{#2}%
     \fi}
    {\begingroup
     \protected@edef\blx@tempc{\endgroup
       \blx@range@out@value{%
         \blx@range@out@item@process{\unexpanded{#1}}%
         \noexpand\bibrangedash
         \blx@range@out@item@process{\unexpanded{#2}}}}%
     \blx@tempc}}
\makeatother

% sections and parts of ancient works shouldn't be compressed
% See SBLHS2 §4.2.6
\DeclareFieldFormat{altpostnote}{\mknormrange{#1}}

\begin{document}

\section*{Examples from SBLHS §4.2.4}

3–9, 11–17, 53–55, 94–113

100–103, 500–508, 502–8, 1100–1187

285–89, 306–23, 809–902, 1003–7

327–35, 448–503, 1465–89, 1698–1703

\medskip

\mkcomprange{3-9, 11-17, 53-55, 94-113}

\mkcomprange{100-103, 500-508, 502-508, 1100-1187}

\mkcomprange{285-289, 306-323, 809-902, 1003-1007}

\mkcomprange{327-335, 448-503, 1465-1489, 1698-1703}

\section*{Examples from \texttt{biblatex-sbl} issue \texttt{\#114}}

17–18, 59–61

150–51, 1698–99, 1698–701, 1998–2003

1200–1203, 300–301

1601–3, 1601–11, 509–602

\medskip

\mkcomprange{17-18, 59-61}

\mkcomprange{150-151, 1698-1699, 1698-1701, 1998-2003}

\mkcomprange{1200-1203, 300-301}

\mkcomprange{1601-1603, 1601-1611, 509-602}

\end{document}
```

![tex226](https://user-images.githubusercontent.com/6268044/107640390-211dfa00-6cc2-11eb-807a-e37fd3740014.png)

**Comment by folofjc** [comment]
Okay, it looks good to me. I also added a section with the examples from CMOS17 9.61 to make sure it matches those, and it does. To be honest, when the number get real big I don't really like their system. The last one looks weird to me. At some point, when enough digits change, it just looks like you should use all of them. Something like 11984-2002 looks like there is a digit missing in the second number. My brain thinks it is 11984-20002 or something. 

Anyways, here is the MWE with the new examples. I left in the bibliography just to make sure:
```
\documentclass[letterpaper,12pt]{report}
\usepackage[english=american]{csquotes} 
\pagestyle{empty}
\parindent=0pt

\usepackage[style=sbl]{biblatex}

\begin{filecontents}[overwrite]{temp.bib}
   @mvbook{AEL,
      author = {Lichtheim, Miriam},
      title = {Ancient Egyptian Literature},
      shorttitle = {AEL},
      volumes = {3},
      location = {Berkeley},
      publisher = {University of California Press},
      date = {1971/1980},
      shorthand = {AEL},
      options = {skipbib}
   }   
   @book{lichtheim:1976,
      author = {Lichtheim, Miriam},
      title = {Ancient Egyptian Literature},
      shorttitle = {AEL},
      volume = {2},
      location = {Berkeley},
      publisher = {University of California Press},
      date = {1976},
      shorthand = {AEL},
      xref = {AEL},
      options = {skipbiblist}
   }   
   @ancienttext{doomedprince,
      title = {The Doomed Prince},
      pages = {200-203},
      related = {lichtheim:1976},
      relatedoptions = {shorthand=short,usevolume=false,skipbiblist}
   }   
\end{filecontents}

addbibresource{temp.bib}

\makeatletter
\def\blx@comprange@check#1#2{%
  \blx@imc@ifinteger{#1}
    {\blx@imc@ifinteger{#2}
       {\@firstoftwo}
       {\@secondoftwo}}
    {\@secondoftwo}
    {\blx@tempcnta=#1
     \divide\blx@tempcnta by 100
     \multiply\blx@tempcnta by 100
     \multiply\blx@tempcnta by -1
     \advance\blx@tempcnta by #1\relax
     \ifnum\blx@tempcnta=0
       \blx@normrange@process{#1}{#2}%
     \else
       \blx@comprange@comp{#1}{#2}%
     \fi}
    {\begingroup
     \protected@edef\blx@tempc{\endgroup
       \blx@range@out@value{%
         \blx@range@out@item@process{\unexpanded{#1}}%
         \noexpand\bibrangedash
         \blx@range@out@item@process{\unexpanded{#2}}}}%
     \blx@tempc}}
\makeatother

\begin{document}
\null\vfill
Test.\autocite{doomedprince}
\medskip
\section*{Examples from SBLHS §4.2.4}

3–9, 11–17, 53–55, 94–113

100–103, 500–508, 502–8, 1100–1187

285–89, 306–23, 809–902, 1003–7

327–35, 448–503, 1465–89, 1698–1703

\medskip

\mkcomprange{3-9, 11-17, 53-55, 94-113}

\mkcomprange{100-103, 500-508, 502-508, 1100-1187}

\mkcomprange{285-289, 306-323, 809-902, 1003-1007}

\mkcomprange{327-335, 448-503, 1465-1489, 1698-1703}

\section*{Examples from \texttt{biblatex-sbl} issue \texttt{\#114}}

17–18, 59–61

150–51, 1698–99, 1698–701, 1998–2003

1200–1203, 300–301

1601–3, 1601–11, 509–602

\medskip

\mkcomprange{17-18, 59-61}

\mkcomprange{150-151, 1698-1699, 1698-1703, 1998-2003}

\mkcomprange{1200-1203, 300-301}

\mkcomprange{1601-1603, 1601-1611, 509-602}

\medskip

\section*{Examples from CMOS17 \S9.61}

3--10, 71--72, 96--117

100--104, 1100--1113

101--8, 808--33, 1103--4

321--28, 498--532, 1087--89, 1496--500, 11564--615, 12991--3001

\medskip

\mkcomprange{3--10, 71--72, 96--117}

\mkcomprange{100--104, 1100--1113}

\mkcomprange{101--108, 808--833, 1103--1104}

\mkcomprange{321--328, 498--532, 1087--1089, 1496--1500, 11564--11615, 12991--13001}

\clearpage
\printbibliography
\end{document}
```
![Screenshot from 2021-02-12 07-46-40](https://user-images.githubusercontent.com/4741202/107738208-8abff780-6d06-11eb-8de7-0f5c29f8fbf9.png)

**Comment by dcpurton** [comment]
I've added this to my new version of `biblatex-sbl`. I'll probably also make a commit to this old version, but I'll wait a little in case you hear back from your question to SBL. I'm not likely to do another release of the current version though. It has become too difficult to support all the bug fixes raised in the blog (which is why I opted for a complete rewrite).

I should really get around to putting my new efforts on GitHub.

BTW, an unrelated question to the problem at hand, but one that occurs to me because you used the Doomed Prince example.

Are you familiar with this kind of work (SBLHS2 §6.4.1.2)?

When I first did this I assumed that for some unknown reason the first citation used the full citation for the book (Miriam Lichtheim…) and subsequent citations should use the *AEL* citation. I'm no longer sure about this as the blog seems to have a preference for always using abbreviations and putting the abbreviation in the list of abbreviations. So no I'm wondering if this is just two different ways of doing the same thing. The first version been for the case when *AEL* doesn't appear in a list of abbreviations, and the second been when it does. If you know better, I'd be interested to hear.

**Comment by folofjc** [comment]
Okay cool. Yeah, totally not worth it to add to the old one. 

No, I am not familiar with this book. I use ANET, though, and the blog agrees with what you are saying for ANET. I don't know if AEL is "well known" enough to put in the abbreviations. My understanding of the blog is for things where it is well known, you put it in the abbreviations and not in the bibliography. But SHLHS2 has like 80 pages of abbreviations. I am not sure that _all_ of those are so well known that they don't go in the bibliography (but I could be wrong). But I agree with your reading. I would either use "AEL" in both instances (even the first citation), or not at all. I think that if you put something in your abbreviation list, you are always supposed to use the abbreviation. This is my understanding of those blog entries. I think that what is in SBLHS2 is not up to date with the blogs, so I wouldn't worry if they contradict.
