### ISSUE TITLE
[help wanted] Formatting chapters and sections?

### ISSUE THREAD

**Issue by folofjc** [dcpurton/biblatex-sbl#116]
@dcpurton, what do you recommend we use instead of `titlesec` for formatting titles and sections when using `biblatex`? 

I posted [this question](https://tex.stackexchange.com/questions/601824/easy-fix-for-biblatex-titlesec-and-citereset) over at `tex.se`, but didn't know if you had any suggestions? (Interestingly, my style guide disagrees with 2.1.3.1 from SBLHS2.)

**Comment by dcpurton** [comment]
Glad the Stack Exchange Question answer suits you. That's the best place for this kind of question.

**Comment by folofjc** [comment]
Yeah, my question here wasn't so much a way to solve that, but more along the lines of since you had to deal with chapters and sections in `sbl-paper`, I wasn't sure if you knew of a "better" way. The answer was easy, but there could very well be other problems that I have not yet come across.

**Comment by dcpurton** [comment]
Not really :). I mainly intended the `sbl-paper` style to be an example of how you might use `biblatex-sbl`.
