### ISSUE TITLE
Abbreviations not in Italics

### ISSUE THREAD

**Issue by folofjc** [dcpurton/biblatex-sbl#117]
Per the `biblatex-sbl` document page 15 under `shorthand`, it states that if both `shorthand` and `shorttitle` are the same, then it assumes that `shorthand` is short for the title and therefore should be italicized. This works in footnotes, but not in the list of abbreviations.  Here is a MWE:

```
\documentclass[letterpaper,12pt]{book}
\usepackage{polyglossia}
\setmainlanguage[variant=us]{english}
\usepackage[english=american]{csquotes} 

\begin{filecontents}[overwrite]{customstyles.dbx}
  \DeclareDatamodelEntrytypes{tdict}
\end{filecontents}

\usepackage[style=sbl,citepages=omit,fullbibrefs=true,sblfootnotes=false,citereset=chapter]{biblatex}

\begin{filecontents}[overwrite]{temp.bib}
@mvlexicon{TDOT,
   title = {Theological Dictionary of the Old Testament},
   shorthand = {TDOT},
   shorttitle = {TDOT},
   editor = {G. Johannes Botterweck and Helmer Ringgren and Heinz-Josef Fabry},
   translator = {David E. Green},
   volumes = {15},
   publisher = {Eerdmans},
   date = {1977/2006},
   address = {Grand Rapids}
}
@inlexicon{TDOT:heaven,
   xref = {TDOT},
   author = {G. Bartelmus},
   title = {Hebrew Name},
   volume = {15},
   pages = {204-236}
}


\end{filecontents}

\addbibresource{temp.bib}

\usepackage{xparse}

\begin{document}

\printbiblist{shorthand}
\null\vfill
Cite a dictionary.\footcite[207]{TDOT:heaven}

\clearpage
\printbibliography
\end{document}
```

![Screenshot 2021-06-19 202436](https://user-images.githubusercontent.com/4741202/122651972-6fde1380-d13c-11eb-9ad9-54d6f7583908.png)

See SBLHS2 page 255 for TDOT showing that in a list of abbreviations it should still be italicized. 

I don't know what a general rule should be, but I think if it is italicized in the footnote, then it should be italicized in the list of abbreviations.

**Comment by folofjc** [comment]
Ugh, my fault. I was used `shorthands` (out of habit) and not `abbreviations`. Just looked at the `.tex` file of the documentation and saw the correct way to do it.

**Comment by dcpurton** [comment]
Yep. I noted in my comment on your other issue that in the next version, I'm going to move away from the `shorttitle`/`shorthand` combination on the grounds that it's excessively confusing.

**Comment by folofjc** [comment]
Interestingly, there appears to be an error in SBLHS2 for hte case of GKC. On page 189 where it is listing abbreviations by Source, GKC is not italicized. But on pg 234 where it is listing them by Abbreviation, it is italicized. I think it is wrong on pg 234. Since GKC is an abbreviation for the editors and translator, I think it should not be italicized.
