### ISSUE TITLE
Shortitle overrides Title in Bibliography

### ISSUE THREAD

**Issue by SClarkWT** [dcpurton/biblatex-sbl#12]
```
@book{SBLHS2,
	Call-Number = {PN147.S26 2014},
	Date-Added = {2016-01-13 18:16:31 +0000},
	Date-Modified = {2016-01-16 19:13:47 +0000},
	Edition = {2},
	Editor = {Billie Jean Collins and Bob Buller and John F. Kutsko},
	Isbn = {9781589839649},
	Location = {Atlanta},
	Publisher = {SBL},
	Read = {1},
	Shorttitle = {SBLHS2},
	Title = {The SBL Handbook of Style: For Biblical and Related Studies},
	Year = {2014}}
```

Will print

> Collins, Buller, and Kutsko, *SBLHS2*, 2nd ed., Atlanta: SBL, 2014.

It should default to ```title``` in the Bibliography.

The subsequent citation footnote looks like it handles ```shortitle``` correctly.

**Comment by SClarkWT** [comment]
this has something to do with me adding the code below in the preamble. 

I am mainly needing single-spacing.

```
\defbibenvironment{bibliography
  {\singlespacing
  \list
     {}
     {\setlength{\leftmargin}{0.5in}%
      \setlength{\itemindent}{-\leftmargin}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}}}
  {\endlist}
  {\item}
```

**Comment by Nhapsie** [comment]
Each university lays out specific requirements for page format. For me it's this: 

```
% Bibliography 

\singlespace
\vskip 0.01\baselineskip

\renewenvironment{thebibliography}[1]
     {\chapter{\bibname}%
      \@mkboth{\MakeUppercase\bibname}{\MakeUppercase\bibname}%
      \addcontentsline{toc}{chapter}{\bibname}%
      %\addcontentsline{toc}{chapter}{\Bibliography}%
      %\singlespace
      \list{}%
           {\itemindent -0.5in
            \leftmargin 0.5in
           }%
      \sloppy
      \clubpenalty4000
      \@clubpenalty \clubpenalty
      \widowpenalty4000%
      \sfcode`\.\@m}
     {\def\@noitemerr
       {\@latex@warning{Empty `thebibliography' environment}}%
      \endlist}

\setlength\bibitemsep{2.5\itemsep} % Bibliography entry, paragraph space
```

**Comment by Nhapsie** [comment]
I did not have a problem with the short title override in the bibliography. Your preamble might be the problem. Having said that, each university lays out specific requirements for page format. For me it's this below. Or it may be something else causing the override. 

% Bibliography 

\singlespace
\vskip 0.01\baselineskip

\renewenvironment{thebibliography}[1]
     {\chapter{\bibname}%
      \@mkboth{\MakeUppercase\bibname}{\MakeUppercase\bibname}%
      \addcontentsline{toc}{chapter}{\bibname}%
      %\addcontentsline{toc}{chapter}{\Bibliography}%
      %\singlespace
      \list{}%
           {\itemindent -0.5in
            \leftmargin 0.5in
           }%
      \sloppy
      \clubpenalty4000
      \@clubpenalty \clubpenalty
      \widowpenalty4000%
      \sfcode`\.\@m}
     {\def\@noitemerr
       {\@latex@warning{Empty `thebibliography' environment}}%
      \endlist}

\setlength\bibitemsep{2.5\itemsep} % Bibliography entry, paragraph space
I am not good at coding, and it probably could be improved, but it works.

**Comment by dcpurton** [comment]
Try adding `\citereset` into your definition (otherwise it still thinks you want the shorttitle) This causes me to wonder if I need to put this somewhere else. But it will work around your problem for now.

```
\defbibenvironment{bibliography}
  {\singlespacing
  \citereset
  \list
     {}
     {\setlength{\leftmargin}{0.5in}%
      \setlength{\itemindent}{-\leftmargin}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}}}
  {\endlist}
  {\item}
```

**Comment by dcpurton** [comment]
I've moved my custom code out of `\defbibenvironment` and into an `\AtBeginBibliography` so it should now be possible to redefine the bibliography environment as you have done above without side effects.

**Comment by dcpurton** [comment]
@SClarkWT: is this fixed? Can I close this issue?

**Comment by SClarkWT** [comment]
Yes!
