### ISSUE TITLE
COS citation duplicates the volume number

### ISSUE THREAD

**Issue by lyndondrake** [dcpurton/biblatex-sbl#123]
I *think* I'm doing everything correctly – at least, as far as I can see my `bib` entries and citation match the examples, but the volume number ends up being duplicated in the citation. The example below should I think have (*COS* 4.17:81) but instead has (COS 4 4.17:81) (I also think the COS should be italicised but isn't). 

```
\documentclass{article}
\usepackage[style=sbl, citepages=omit,]{biblatex}
\addbibresource{~/repo/workflow/Test/biblatex-sbl-test/cos-bib.bib}
            
\begin{document}
\cite{COS:4.17}
\end{document}
```

`.bib` file:
```
@mvcollection{COS,
  title = {The Context of Scripture},
  shorttitle = {{{COS}}},
  editor = {Hallo, William W. and Younger, K. Lawson},
  date = {2003},
  publisher = {{Brill}},
  location = {{Leiden}},
  file = {/Users/lyndon/Documents/Media/Bookshelf/Hallo2003 The context of scripture.pdf},
  options = {skipbib},
  volumes = {4},
  shorthand = {COS}
}
@collection{COS:4,
  title = {Supplements},
  shorttitle = {{{COS}}},
  editor = {Younger, K. Lawson},
  date = {2016},
  volume = {4},
  publisher = {{Brill}},
  location = {{Leiden}},
  maintitle = {The Context of Scripture},
  options = {skipbiblist},
  shorthand = {COS},
  xref = {COS}
}
@ancienttext{COS:4.17,
  title = {Barley Order},
  shorttitle = {Barley Order},
  volume = {4},
  pages = {81},
  entrysubtype = {COS},
  part = {17},
  related = {COS:4},
  relatedoptions = {usevolume=false,skipbiblist},
  translator = {Suriano, Matthew}
}
```

Output:

<img width="287" alt="Screenshot 2021-07-01 at 3 29 44 PM" src="https://user-images.githubusercontent.com/18509357/124060439-2ae1a780-da81-11eb-9bd9-02221931f5c6.png">

**Comment by dcpurton** [comment]
Ha! That took me a while to spot.

Remove the `volume` field from `COS:4.17`. It's also picking it up from `COS:4` and so printing it twice.

Also take away your multiple braces around `COS` in the `shorttitle` of your `COS` entry. This is messing up the printing of COS which should be in italics.

**Comment by lyndondrake** [comment]
That does indeed fix it. Thank you! The multiple braces comes from the Zotero export so I'll figure out how to remove that. I might end up just creating a separate `.bib` file for the `ancienttext` as the amount of customisation I'm having to do the Zotero export is reducing its usefulness… Up until now it has been great as I can just cite from the `.json` in Pandoc Word document conversions using the identical citekey for the LaTeX document but the `ancienttext` ones are a bit tricksy.

It might be worth amending the example in your `examples.pdf` to not include the volume:

```
@ancienttext{greathymnaten,
entrysubtype = {COS},
title = {The Great Hymn to the Aten}, shorttitle = {Great Hymn to the Aten}, translator = {Lichtheim, Miriam},
volume = {1},
part = {26},
pages = {44-46},
related = {hallo:1997},
relatedoptions = {usevolume=false,skipbiblist}
}
```
