### ISSUE TITLE
Sponsor?

### ISSUE THREAD

**Issue by folofjc** [dcpurton/biblatex-sbl#132]
@dcpurton this package has been super helpful, and your help has been indispensable both here and at tex.se. I went to your profile to try to do a github sponsorship thing, but I guess you haven't turned that on? If you turn it on, I'd be glad to support your work!

[info](https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/setting-up-github-sponsors-for-your-personal-account)

**Comment by dcpurton** [comment]
@folofjc , hehe. Thank you (although I do work on LaTeX projects just for fun).

I'll have a look at setting up GitHub sponsorship.

If you're super keen, another way of supporting me is through [AFES](https://afes.org.au), the organisation I work for doing Christian university student ministry. My role is 100% supported by friends and family who give towards the work. Donations for me can be done [online in Australian dollars via credit card](https://support.afes.org.au/support-david-purton-focus-adelaide-2869).

**Comment by folofjc** [comment]
Done!
