### ISSUE TITLE
Include all entries from .bib file in the bibliography

### ISSUE THREAD

**Issue by RyanQuey** [dcpurton/biblatex-sbl#136]
First of all, thanks for the great library, and well put together examples. 

I wasn't able to find though: Is there a way to use the `\printbibliography` command to construct a complete bibliography, that includes all entries in the .bib file (not just those cited in footnotes)?

Thanks in advance

**Comment by dcpurton** [comment]
Hi Ryan, 

Yes, you can use `\nocite{*}` anywhere in your document and all the entries will be added to the bibliography. 

David

**Comment by RyanQuey** [comment]
That solved it, thanks very your help!
