### ISSUE TITLE
Is there an option for full page ranges instead of SBL abbreviated ones?

### ISSUE THREAD

**Issue by jackymendez** [dcpurton/biblatex-sbl#138]
Hi @dcpurton, does biblatex-sbl have an option to use full page ranges rather than the standard abbreviated ones? I have looked over the documentation and haven't seen anything but apologies if I missed something obvious. The journal I'm submitting to has a preference for unabbreviated page ranges - so, e.g., in the MWE below, is there a way I can make it so the reference in the bibliography reads "122–134" (as in the .bib entry) instead of modifying it to "122–34"?

```
\documentclass[12pt]{article}

\begin{filecontents}{mybib.bib}
@incollection{bartonDarkSide2010,
  title = {The {{Dark Side}} of {{God}} in the {{Old Testament}}},
  shorttitle = {Dark {{Side}}},
  booktitle = {Ethical and {{Unethical}} in the {{Old Testament}}: {{God}} and {{Humans}} in {{Dialogue}}},
  author = {Barton, John},
  editor = {Dell, Katharine J.},
  date = {2010},
  series = {The {{Library}} of {{Hebrew Bible}}/{{Old Testament Studies}}},
  number = {528},
  pages = {122--134},
  publisher = {T\&T Clark International},
  location = {New York},
  shortseries = {LHBOTS}
}
\end{filecontents}


\usepackage[style=sbl, usefullcite=false, citepages=omit]{biblatex} 
\addbibresource{mybib.bib}


\usepackage{xpatch}

\xpatchbibmacro{cite}
{\ifciteseen{}{\iffieldundef{pages}{}{\booltrue{suppresspostnote}}}}
{\ifciteseen{}{\iffieldundef{pages}{}{%
   \iftoggle{blx@usefullcite}
     {\booltrue{suppresspostnote}}
     {}}%
  }}
{}
{}

\begin{document}

Full unabbreviated page range present in the citation footnote here, but not in bibliography.\autocite[127--128]{bartonDarkSide2010}

\printbiblist{abbreviations}
\printbibliography

\end{document}  
```

<img width="533" alt="Screenshot 2024-12-23 at 3 12 16 pm" src="https://github.com/user-attachments/assets/85d3b10b-5e98-4868-9614-e74fdbf0a1a2" />

**Comment by dcpurton** [comment]
@jackymendez this is a feature of `biblatex` so not documented in the `biblatex-sbl` documentation. 

Have a look for the counters: `mincomprange`, `maxcomprange` and `mincompwidth`.

If I get a chance later I'll give a full answer.

**Comment by jackymendez** [comment]
D'oh. Thanks for getting back to me!

For anyone else who might stumble upon this, this thread has some good detail: https://tex.stackexchange.com/questions/23483/how-can-i-automatically-abbreviate-page-ranges-in-citations-biblatex

I just added `\setcounter{mincomprange}{1000000}` to my preamble and it gave me what I was after.
