### ISSUE TITLE
Volume field is out of order in bibliography for ANF and NPNF¹ (§6.4.5 of SBLHS2)

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/biblatex-sbl#14]
Current output:

> *The Ante-Nicene Fathers.* Edited by Alexander Roberts and James Donaldson. 10 vols. 1885–1887. Repr., Peabody, MA: Hendrickson, 1994.
>
> *The Nicene and Post-Nicene Fathers,* Series 1. Edited by Philip Schaff. 14 vols. 1886–1889. Repr., Peabody, MA: Hendrickson, 1994.

Expected output:

> *The Ante-Nicene Fathers.* Edited by Alexander Roberts and James Donaldson. 1885–1887. 10 vols. Repr., Peabody, MA: Hendrickson, 1994.
>
> *The Nicene and Post-Nicene Fathers,* Series 1. Edited by Philip Schaff. 1886–1889. 14. vols. Repr., Peabody, MA: Hendrickson, 1994.

Unfortunately this is to do with a design problem with how I have implemented **§6.2.17  Reprint of a Recent Title** and will take some time to think through and correct.

**Comment by dcpurton** [comment]
Actually, I'm not so sure about this one. I think the handbook is wrong for ANF and NPNF¹. See a selection of examples from the handbook below. These two are the *only* ones putting the volume in this somewhat odd position. In every other case Repr. follows on directly after the original publication date.

Although there is still a question of where the volume should go. In my view it should either go *before* `origdate` if it was originally published in this many volumes, or *after* Repr., if the reprint was published in a different number of volumes than the original. In this latter case though I would think we would want both an `origvolume` and a `volume` specified, with `origvolume` coming before `origdate` and `volume` coming after Repr.

The problem then is that potentially a lot of `orig-` fields would need to be added. I think a better option would be to use a `related` entry and then some way of differentiating between this kind of reprint and a full history citation (§6.2.5).

Thoughts?

> 1. Jack M. Sasson, ed., *Civilizations of the Ancient Near East,* 4 vols. (New York: Scribner’s Sons, 1995; repr., 4 vols. in 2; Peabody, MA: Hendrickson, 2000).
> 
> 2. Thomas O. Lambdin, *Introduction to Classical Ethiopic (Ge‘ez)* (Missoula, MT: Scholars Press, 1978; repr., HSS 24; Winona Lake, IN: Eisenbrauns, 2006)
> 
> 3. Gustav Adolf Deissmann, *Light from the Ancient East: The New Testament Illustrated by Recently Discovered Texts of the Graeco-Roman World* (trans. Lionel R. M. Strachan; 1927; repr., Peabody, MA: Hendrickson, 1995), 55.
> 
> Deissmann, Gustav Adolf. *Light from the Ancient East: The New Testament Illustrated by Recently Discovered Texts of the Graeco-Roman World.* Translated by Lionel R. M. Strachan. 1927. Repr., Peabody, MA: Hendrickson, 1995.
> 
> Dossin, Georges. *Lettres.* ARM 1. 1946. Repr., Paris: Geuthner, 1967.
> 
> *The Ante-Nicene Fathers.* Edited by Alexander Roberts and James Donaldson. 1885–1887. 10 vols. Repr., Peabody, MA: Hendrickson, 1994.
> 
> Augustine. *The Letters of St. Augustin.* In vol. 1 of *The Nicene and Post-Nicene Fathers,* Series 1. Edited by Philip Schaff. 1886–1889. 14 vols. Repr., Peabody, MA: Hendrickson, 1994.
> 
> *Acta Martyrum et Sanctorum Syriace.* Edited by Paul Bedjan. 7 vols. Paris, Leipzig: Harrassowitz, 1890–1897. Repr., Hildesheim: Olms, 1968.
> 
> *Ancient Records of Assyria and Babylonia.* Daniel David Luckenbill. 2 vols. Chicago: University of Chicago Press, 1926–1927. Repr., New York: Greenwood, 1968.
> 
> *Ancient Records of Egypt.* Edited by James Henry Breasted. 5 vols. Chicago: University of Chicago Press, 1906–1907. Repr., New York: Russell & Russell, 1962.
> 
> *The Beginnings of Christianity.* Part 1: *The Acts of the Apostles.* Edited by Frederick J. Foakes-Jackson and Kirsopp Lake. 5 vols. London: Macmillan, 1922. Repr. under the subtitle, Grand Rapids: Baker, 1977.
> 
> *Civilizations of the Ancient Near East.* Edited by Jack M. Sasson. 4 vols. New York, 1995. Repr. in 2 vols. Peabody, MA: Hendrickson, 2006.
> 
> Duchesne, Louis, ed. *Le Liber pontificalis.* 2 vols. Paris: Thorin, 1886,
> 1892. Repr. with 3rd vol. by Cyrille Vogel. Paris: de Boccard, 1955–1957, 1981.
> 
> *Encyclopedia of Religion and Ethics.* Edited by James Hastings. 13 vols. New York: Scribner’s Sons, 1908–1927. Repr., 7 vols. 1951.
> 
> *Grundriss der vergleichenden Grammatik der semitischen Sprachen.* Carl Brockelmann, 2 vols. Berlin: Reuther & Reichard; New York: Lemcke & Buechne, 1908–1913. Repr., Hildesheim: Olms, 1961.
> 
> Keil, Carl Friedrich, and Franz Delitzsch. *Biblical Commentary on the Old Testament.* Translated by James Martin et al. 25 vols. Edinburgh, 1857–1878. Repr., 10 vols., Peabody, MA: Hendrickson, 1996.
> 
> Lane, Edward W. *An Arabic-English Lexicon.* 8 vols. London: Williams & Norgate, 1863. Repr., Beirut: Libr. du Liban, 1980.
> 
> Wehr, Hans. *A Dictionary of Modern Written Arabic.* Edited by J. Milton Cowan. 3rd ed. Ithaca: Spoken Languages Services, 1976. Repr., 4th enlarged and amended ed., Wiesbaden: Harrassowtiz, 1979.
> 
> *Wörterbuch der ägyptischen Sprache.* Adolf Erman and Hermann Grapow. 5 vols. Leipzig: Hinrichs; Berlin: Akademie, 1926–1931. Repr., 1963.
> 
> *Das Wörterbuch über die Talmudim und Midraschim.* Jacob Levy. 2nd ed. Berlin: Harz, 1924. Repr., 1963.

**Comment by baem2** [comment]
I think the "Current Output" in your first post is better than the "Expected" one, so just leave it as it is.

**Comment by dcpurton** [comment]
Latest version supports 3 different ways of doing reprints:

1. Only original location, publisher, and/or year required. e.g.,

   ```bib
@book{vanseters:1997,
        author = {Van Seters, John},
        title = {In Search of History: Histeriography in the Ancient World and
        the Origins of Biblical History},
        origlocation = {New Haven},
        origpublisher = {Yale University Press},
        origdate = {1983},
        location = {Winona Lake, IN},
        publisher = {Eisenbrauns},
        date = {1997}
}
   ```

   > ⁷John Van Seters, *In Search of History: Histeriography in the Ancient World and the Origins of Biblical History* (New Haven: Yale University Press, 1983; repr., Winona Lake, IN: Eisenbrauns, 1997), 80.
   >
   > ⁸Van Seters, *In Search of History,* 90.
   >
   > Van Seters, John. *In Search of History: Histeriography in the Ancient World and the Origins of Biblical History.* New Haven: Yale University Press, 1983. Repr., Winona Lake, IN: Eisenbrauns, 1997.

2. When extra information for the reprint is required, use a related entry with `relatedtype = {reprint}`. (A custom string can be specified instead of “Repr.” using the optional `relatedstring` field. In this case no punctuation is inserted after the `relatedstring`. You could think of the default being `relatedstring = {\bibstring{reprint},}`.) e.g.,

   ```
@mvbook{sasson:2000,
        editor = {Sasson, Jack M.},
        title = {Civilizations of the Ancient Near East},
        volumes = {4},
        location = {New York},
        publisher = {Scribner's Sons},
        year = {1995},
        related = {sasson:repr},
        relatedtype = {reprint}
}
@mvbook{sasson:repr,
        volumes = {4~vols.\ in 2},
        location = {Peabody, MA},
        publisher = {Hendrickson},
        date = {2000}
}
   ```

   > ³Jack M. Sasson, ed., *Civilizations of the Ancient Near East,* 4 vols. (New York: Scribner’s Sons, 1995; repr., 4 vols. in 2; Peabody, MA: Hendrickson, 2000), 1:40.
   >
   > ⁴Sasson, *Civilizations of the Ancient Near East,* 2:50.
   >
   > Sasson, Jack M., ed. *Civilizations of the Ancient Near East.* 4 vols. New York: Scribner’s Sons, 1995. Repr., 4 vols. in 2. Peabody, MA: Hendrickson, 2000.

3. Full reprint history is also done using the `related` field, but with some other `relatedtype` apart from `relatedtype = {reprint}`. e.g.,

   ```
@book{wellhausen:1883,
        author = {Wellhausen, Julius},
        title = {Prolegomena zur Geschichte Israels},
        edition = {2},
        location = {Berlin},
        publisher = {Reimer},
        date = {1883}
}
@book{wellhausen:1885,
        author = {Wellhausen, Julius},
        title = {Prolegomena to the History of Israel},
        translator = {Black, J. Sutherland and Enzies, A.},
        preface = {Smith, W. Robertson},
        location = {Edinburgh},
        publisher = {Black},
        related = {wellhausen:1883},
        relatedtype = {translationof},
        date = {1885}
}
@book{wellhausen:1957,
        author = {Wellhausen, Julius},
        title = {Prolegomena to the History of Ancient Israel},
        location = {New York},
        publisher = {Meridian Books},
        related = {wellhausen:1885},
        relatedtype = {reprintof},
        date = {1957}
}
   ```

   > ¹Julius Wellhausen, *Prolegomena to the History of Ancient Israel* (New York: Meridian Books, 1957), 20; repr. of *Prolegomena to the History of Israel,* trans. J. Sutherland Black and A. Enzies, with preface by W. Robertson Smith (Edinburgh: Black, 1885); trans. of *Prolegomena zur Geschichte Israels,* 2nd ed. (Berlin: Reimer, 1883).
   >
   > ²Wellhausen, *Prolegomena to the History of Ancient Israel,* 30.
   >
   > Wellhausen, Julius. Prolegomena to the History of Ancient Israel. New York: Meridian Books, 1957. Reprint of Prolegomena to the History of Israel. Translated by J. Sutherland Black and A. Enzies, with preface by W. Robertson Smith. Edinburgh: Black, 1885. Translation of *Prolegomena zur Geschichte Israels,* 2nd ed. Berlin: Reimer, 1883.

## Notes

This implementation differs from the SBLHS in that:

* it does not allow for any field to go between the original date and “Repr.” (cf. SBLHS2 §6.4.5).
* it does not put extra fields associated with the original edition within parentheses (cf. SBLHS2 §6.2.18).

This breaks backwards compatibility in that:

* `origtranslator` and `origeditor` are no longer supported.
* `relatedtype = {reprint}` now behaves differently to any other `relatedtype`

I think this can handle all the reprint examples I can find in the SBLHS.
