### ISSUE TITLE
Complete page numbers

### ISSUE THREAD

**Issue by baem2** [dcpurton/biblatex-sbl#15]
biblatex-sbl seems to cut off page numbers in page ranges, i.e. if in the bib file I give 145--151, it will be printed as: '145--51'.

Is there a way to change that behaviour, via a global option or something?

I know that this behaviour differs from the SBLHS, but there are some journals (like NovT) that are using "derivatives" of the SBLHS ...

**Comment by dcpurton** [comment]
Yes. This is easy to change.

See the biblatex documentation for the counters `mincomprange`, `maxcomprange`, and `mincompwidth`. There is a useful table (Tale 10) on page 196 of the biblatex manual that illustrates the effect of each counter.

Just redefine the counters in your preamble.

**Comment by baem2** [comment]
I see -- thanks!
