### ISSUE TITLE
SBL Seminar Papers & In Collection

### ISSUE THREAD

**Issue by SClarkWT** [dcpurton/biblatex-sbl#17]
Since ```seminarpaper``` is essentially identical to ```incollection```, is there any reason it's differentiated?

**Comment by Nhapsie** [comment]
There are several differences, compare the two. Check David’s SBLRef.pdf

Incollection:

3. Harold W. Attridge, “Jewish Historiography,” in Early Judaism and Its Modern Interpreters, ed. Robert A. Kraft and George W. E. Nickelsburg (Philadel- phia: Fortress; Atlanta: Scholars Press, 1986), 311–43.

6. Attridge, “Jewish Historiography,” 314–17.

Attridge, Harold A. “Jewish Historiography.” Pages 311–43 in Early Judaism and Its Modern Interpreters. Edited by Robert A. Kraft and George W. E. Nickelsburg. Philadelphia: Fortress; Atlanta: Scholars Press, 1986.

SBLSeminar:

33. James L. Crenshaw, “Theodicy in the Book of the Twelve,” Society of Biblical Literature 2001 Seminar Papers, SBLSPSa 40 (Atlanta: Society of Biblical Literature, 2001), 1–18.

Crenshaw, James L. “Theodicy in the Book of the Twelve.” Pages 1–18 in Society of Biblical Literature 2001 Seminar Papers. SBLSPSa 40. Atlanta: Society of Biblical Literature, 2001.

**Comment by SClarkWT** [comment]
Ah I see the difference, easy to miss.
