### ISSUE TITLE
Localisation issues

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/biblatex-sbl#19]
I need a thread to discuss localisation issues:

In the SBLHS long dates are formatted thus: **20 December 1992**

Curiously, this matches what we do in Australia, but I think is different to what is common in the US.

@SClarkWT, can you offer some thoughts on how long dates should be formatted in Spanish?
By default BibLaTeX will use: **20 de diciembre 1992** The current `sbl-spanish.lbx` file includes code to modify this to: **20 diciembre 1992** (same code as produces the SBL format in English).

Similarly, @baem2, what should happen in German? The BibLaTeX default gives **20. Dezember 1992** while the current `sbl-german.lbx` file gives **20 Dezember 1992**

And @Nhapsie, what about in Brazil? Default is **20 de dezembro de 1992**. Is that better than **20 dezembro 1992**?

Should we drop the custom date code from the all the language files except `sbl-american.lbx`?

**Comment by baem2** [comment]
In German it should be ``20. Dezember 1992`` (note the dot behind the 20).

**Comment by SClarkWT** [comment]
@dcpurton from what I can tell of Spanish examples for Chicago they all use "15 de diciembre"

I guess we will need to figure out how to avoide date override.

**Comment by dcpurton** [comment]
Actually it's easy. Just remove the date redefinition in `\DeclareBibliographyExtras`. It's late here now. I'll do it tomorrow and push the change. The lbx files have a couple of problems I found that need fixing.

**Comment by Nhapsie** [comment]
Yes, in Brazil is “20 de dezembro de 1992” but other dates are acceptable as in “20 dezembro 1992”. This is a moot point, as any seminary in Brazil can choose one or the other frankly. And there’s also the Brazilian Association of Format for Academic Work which sometimes do not follow SBL in its entirety. It’s better to use standard and change per situation as needed.
