### ISSUE TITLE
Parentheses around editors incollection

### ISSUE THREAD

**Issue by kennylarsen** [dcpurton/biblatex-sbl#2]
Hi Dave,

Many Thanks for all the work. I've noted that according to SBLHS 7.2.12 (and similar), when you have an article/ chapter in an edited work the parentheses should extend to include all the editor information. Currently they only extend only around the publisher, location and date. I've hacked at you DeclareBibliographyDriver for incollection to get what appears correct output and included the code below. However, I don't really have much idea what I'm doing - I just guessed/ copied things from elsewhere in your code - so there may be a better way. Anyway, I hope this helps.

Kenny

\DeclareBibliographyDriver{cite:incollection}{%
  \usebibmacro{usesblxref}%
  \usebibmacro{author/editor+others/translator+others}%
  \newunit
  \usebibmacro{title}%
  \ifciteseen
    {}
    {\usebibmacro{in}%
     \renewcommand*{\newunitpunct}{\space}%
     \usebibmacro{booktitle}%
     \printtext[parens]{%
     \usebibmacro{bybookeditor+others}%
     \setunit*{\newunitpunct}%
     \usebibmacro{volumeof}%
     \usebibmacro{maintitle}%
     \newunit
     \usebibmacro{bymaineditor+others}%
     \newunit
     \printfield{volumes}%
     \newunit
     \printfield{edition}%
     \newunit
     \usebibmacro{shortseries+number}%
     \setunit{\addspace}%
       \renewcommand*{\newunitpunct}{\addsemicolon\space}%
       \newunit
       \usebibmacro{publisher+location+date}%
     }%
     \newunit
     \usebibmacro{volume+part+pages}%
     \newunit
     \usebibmacro{doi+eprint+url}}}

**Comment by Nhapsie** [comment]
Hi Kenny, are you sure you’re using SBLHS 2? It would seem to me you’re using version 1. 

Best, 
Nhaps

**Comment by dcpurton** [comment]
Hi Kenny,

Thanks for the comments. It does look like you are referring to the first edition of the SBLHS. I've chosen not to support this for the moment at least. Moving extra details out of the parentheses is one of the major changes between the first and second edition. See http://www.sbl-site.org/publications/SBLHandbookofStyle.aspx

There do some to be a couple of exceptions to this: 6.2.18 (A Reprint Title in the Public Domain) and 6.3.8 (A Paper Presented at a Professional Society). But all the rest of the examples in the second edition of the SBLHS only contain location, publisher, and date within parentheses.

Hope that helps.

Feel free to fork and work on an option to support the first edition. Perhaps you could support an edition global option for the style:

\usepackage[sbl,edition=1]{biblatex}

Thanks,

David

**Comment by kennylarsen** [comment]
Hi David and Nhaps,

Thanks, and apologies that is entirely my fault for not checking correctly and presuming my university were using the latest SBLHS! I may well make a fork for that once the next set of essays are finished!

Thanks,


Keny
