### ISSUE TITLE
inbook/incollection and bookauthor

### ISSUE THREAD

**Issue by baem2** [dcpurton/biblatex-sbl#21]
Currently, if a inbook or incollection has a bookauthor given, that bookauthor is not printed at all (only the bookeditor is printed). Would it be possible to print the author as well, similar to the "Introduction" case, where you have ``AUTHOR, introduction to BOOKTITLE by BOOKAUTHOR ...``? So that you have for inbook/incollection: ``AUTHOR, "TITLE," BOOKTITLE by BOOKAUTHOR ...`.

That gives more flexibility for cases where BOOKAUTHOR wrote a book (so he is not an editor), but someone else wrote a little chapter or something (but it's not an "introduction to").

**Comment by Nhapsie** [comment]
I don’t remember seeing an instance in SBLHS 2 where book author is included for incollection. Probably inbook yes, but so far I never found the need to include one. Give us a reference example.

**Comment by baem2** [comment]
Well, there are many publications with a varying degree of complextiy. For example this one by Peterson/Markschies:
```
@INBOOK{markschies_hildebrandt:addenda,
	author = {Markschies, Christoph AND Hildebrandt, Henrik},
	title = {Addenda et Corrigenda},
	bookauthor = {Peterson, Erik AND Markschies, Christoph},
	pages = {365--580},
	booktitle = {HEIS THEOS},
	booksubtitle = {Epigraphische, formgeschichtliche und religionsgeschichtliche Untersuchungen zur antiken Ein-Gott-Akklamation},
	booktitleaddon = {Nachdruck der Ausgabe von Erik Peterson 1926 mit Ergänzungen und Kommentaren von Christoph Markschies, Henrik Hildebrandt, Barbara Nichtweiß u.a. 2012},
	series = {Erik Peterson: Ausgewählte Schriften},
	number = {8},
	location = {Regensburg},
	year = {2012}
}
```

http://downloads.bistummainz.de/5/415/1/51043066299176944231.pdf

A similar case is this one by Theißen:
http://digi20.digitale-sammlungen.de/de/fs1/object/display/bsb00048630_00002.html

**Comment by Nhapsie** [comment]
As far as I know, the problem is that in both pdf instances below, the SBLHS will not include the book’s author as a new field in addition to the author of a part of it. At least this seems to be the case in the US. Are you bound to continental standard? I would not know how this is handled in Europe. This is something I would likely ask David.

**Comment by dcpurton** [comment]
Don't worry, Carlos. This is pretty easy to add. If the entry includes `bookauthor` it will print, if it doesn't, then nothing will change. I'll do it later today.

**Comment by Nhapsie** [comment]
Good, that will make Philipp happy.

**Comment by dcpurton** [comment]
@baem2, can you try the latest version? Does that do what you want?

**Comment by baem2** [comment]
Yap, great, thank you!
