### ISSUE TITLE
Package keyval Error: ibidpage undefined.

### ISSUE THREAD

**Issue by SClarkWT** [dcpurton/biblatex-sbl#22]
Is anyone else getting this error?

`/usr/local/texlive/2015/texmf-dist/tex/latex/biblatex/biblatex_.sty:11475: Package keyval Error: ibidpage undefined.`
`See the keyval package documentation for explanation.
Type  H <return>  for immediate help.`

Elsewhere someone said that this showed up in biblatex-chicago so I wonder if maybe it's appearing here too. https://groups.google.com/forum/#!msg/comp.text.tex/-3zyI_wbM_Y/to2oaQZ5kjUJ

**Comment by dcpurton** [comment]
Yeah. I removed the option because I discovered it wasn't actually donning anything... :)

A better question is whether ibid is behaving in the way you want. I can put ibidpage back in again, but thought for now it was better to not pretend to support it.

**Comment by SClarkWT** [comment]
I removed the option and it cleared the error. Thanks

Personally I don't need Ibid. since it's not required or recommended by SBLHS2. But others may.

**Comment by Nhapsie** [comment]
I know, it varies within university departments. I am using it.

**Comment by dcpurton** [comment]
@Nhapsie are you also using the ibidpage option?

The standard biblatex styles define this option in this way:

> **The `ibidpage` option**
>
> The scholarly abbreviation *ibidem* is sometimes taken to mean both ‘same author + same title’ and ‘same author + same title + same page’ in traditional citation schemes. By default, this is not the case with this style because it may lead to ambiguous citations. If you you prefer the wider interpretation of *ibidem*, set the package option `ibidpage=true` or simply `ibidpage` in the preamble. The default setting is `ibidpage=false`.

I don't think setting `ibidpage` to `true` or `false` has ever had any affect in `biblatex-sbl` (even though up until recently you could use it).

I think I need a good test file for *ibidem* usage.

@Nhapsie, you know better than me how *ibidem* is meant to work. Are you able to put together a simple file of a few pages using some of the example references in `biblatex-sbl.bib` and see what the style currently spits out? We want to test what happens in as many different combinations as you can think of including what happens across page breaks.

**Comment by dcpurton** [comment]
Hey, how about that! the `ibidpage` *did* work! I'll add it back, but set it to false by default as the standard styles do. :)

**Comment by dcpurton** [comment]
fixed and an ibid test file added.

**Comment by Nhapsie** [comment]
SBL Handbook v.2 uses ibid as abbreviation of ibidem, hence they are one and the same in the handbook. Plain ibid means author+title+page, and if page differs, we use "Ibid, 25." for example. It is this simple use of Ibid that works for my university.
