### ISSUE TITLE
Changes to name formats in biblatex 3.3

### ISSUE THREAD

**Issue by moewew** [dcpurton/biblatex-sbl#23]
Since your style is so actively developed I'm not sure if you don't already know about this, I thought a short heads-up couldn't hurt either way.

In version 3.3 of biblatex the name handling was substantially revised, see https://github.com/plk/biblatex/issues/372 and http://mirrors.ctan.org/macros/latex/contrib/biblatex/RELEASE.

https://github.com/dcpurton/biblatex-sbl/blob/master/latex/biblatex-sbl.def contains some name-related code (especially https://github.com/dcpurton/biblatex-sbl/blob/master/latex/biblatex-sbl.def#L415) that would probably need some changing.

**Comment by dcpurton** [comment]
Hmmm. Thanks for the heads up. Looks like the best option for me will be to depend on biblatex >= 3.3.

**Comment by moewew** [comment]
Since the name handling is to be changed slightly in 3.4 again it might be wise to wait for that. (The only difference is that the call to `\nameparts` becomes useless.) See https://github.com/plk/biblatex/releases/tag/v3.4

**Comment by dcpurton** [comment]
For my reference:

The name format in the Bibliography needs to be: "Hoffner, Harry A., Jr."

The default in biblatex has been "Hoffner Jr., Harry A.,"

The various "with" authors are always first-last format which will become given-family.

These changes are small enough that I'll try to implement things in a way that will work with any version of biblatex.

**Comment by dcpurton** [comment]
Fixed in dev branch. Will continue to work with older versions of biblatex
