### ISSUE TITLE
Entries with both a shorthand and a shortseries do not work for biblatex >= 3.3 and biber >= 2.4

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/biblatex-sbl#26]
biber spits out the following error:

```
Can't call method "get_field" on an undefined value at /tmp/par-6463707572746f6e/cache-ab2aa2ece61cc988b50d107b05c5c3fad9d00256/inc/lib/Biber.pm line 3377.
```

Not sure what this is related to yet, but probably connected with how I'm putting both shortseries and shorthand in the list of abbreviations.

The following minimal working example demonstrates the issue:

```
\documentclass{article}
\usepackage[style=sbl,backend=biber]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{ABC,
  author = {Grayson, Albert Kirk},
  title = {Assyrian and Babylonian Chronicles},
  shorttitle = {ABC},
  series = {Texts from Cuneiform Sources},
  shortseries = {TCS},
  number = {5},
  location = {Locust Valley, NY},
  publisher = {Augustin},
  date = {1975},
  shorthand = {ABC}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\cite{ABC}
\printbibliography
\end{document}
```

**Comment by dcpurton** [comment]
May be a problem with biber/biblatex: https://github.com/plk/biblatex/issues/377

**Comment by Nhapsie** [comment]
Work with biblatex 3.2 and biber 2.3, and move on to next version only if you run into errors. This will avoid bugs that usually come with new version releases.

**Comment by dcpurton** [comment]
Fixed in dev branch. dev branch will continue to work with older versions of biblatex

**Comment by dcpurton** [comment]
This is fixed up stream. biber 2.4 won't work, but biber 2.5 will.
