### ISSUE TITLE
The use of "idem"

### ISSUE THREAD

**Issue by Nhapsie** [dcpurton/biblatex-sbl#28]
I know that we touched on the use of "ibid" a while ago, which refers to same author-work but different page, and this is working fine. But "idem" is not working, which stands for same author but different work. At least I tested it for @book, and it's not active. See page 120 on SBLHS 2.

**Comment by dcpurton** [comment]
Correct. "idem" is not currently supported. I can look at adding it..

**Comment by Nhapsie** [comment]
Great, though this is not urgent we appreciate it.

**Comment by dcpurton** [comment]
Should "idem" be used for the first citation of a work? The default biblatex styles seem to only use it for subsequent citations. e.g.,

`\cite{author:2000}`  ← long citation;
`\cite{author:2001}`  ← long citation; ibid not used
`\cite{author:2000}` ← short citation; ibid used

Also, what about idem and editor?

`\cite{editor:2000}`  ← long citation;
`\cite{author:2001}`  ← long citation; ibid not used
`\cite{editor:2000}` ← short citation; use "ibid, ed.,"?

**Comment by Nhapsie** [comment]
The way I understand it, idem is used in the same footnote only, for immediate second and subsequent instances of the same author. Note that idem spells out the title, in contrast to ibid which does not. If the sequence is broken by author 2, then idem is suspended, and reverts back to author 1. So if the above examples follow in sequence in the same footnote, then I would use idem for both instances of author:2001. As for the short citation author:2000 and editor:2000, they would also take idem if they are the second title of the same author. In my view author and editor should not be differentiated by the use of idem. But if you think they should that's not a problem; just too much work to code it.

**Comment by dcpurton** [comment]
OK. Your understanding seems to match my quick look at CMS (although CMS discourages the use of idem). This departs from the way the standard `biblatex` styles handle *idem* (that's no problem, of course).

This would mean that "idem" would only appear when `\cites`, `\autocites`, or `\parencites` are used to produce multiple citations, right?

Doesn't not using "idem, ed." create the potential for an ambiguous citation, though? If your first citation is for an editor and the next is for the same person, but as an author, you wind up with:

> `\autocites(See)[12]{family:editor}[13]{family:author}`
> 1. See Given Family, ed., *Edited Title* (Location: Publisher, 2000), 12; idem, *Authored Title* (Location: Publisher, 2000), 13.

If you do it the other way round you'll get

> `\autocites(See)[13]{family:author}[12]{family:editor}`
> 1. See Given Family, *Authored Title* (Location: Publisher, 2000), 13; idem, *Edited Title* (Location: Publisher, 2000), 12.

How can you tell the difference in role in the second citations?

(Of course, this situation is likely to e extremely rare...)

**Comment by Nhapsie** [comment]
Yes, "idem" appears only within` \cites` derivatives, for mutiple works of the same author in sequential order in the same footnote. It avoids the name repetition, which is great. 

For me "Idem" is not made to tell us whether the person is author or editor in a given case, it only avoids redundancy in the same sequential footnote. But this opinion might me wrong, it's up for grabs because SBLHS does not touch on the issue. I think this goes back to university guidelines. I think, for this reason, that any improvement would have to fall into a kind of on/off preference as we have for other features in the test file.

**Comment by dcpurton** [comment]
Have a look at the latest dev version and play around with this MWE:

```
\documentclass{article}

\usepackage{filecontents}
\usepackage{hyperref}
\usepackage[style=sbl,idemtracker=constrict,ibidtracker=context,pagetracker,ibidpage,backend=biber]{biblatex}

\begin{filecontents}{\jobname.bib}
@commentary{dahood:1965,
  author = {Dahood, Mitchell},
  title = {Psalms I: 1--50},
  shorttitle = {Psalms I: 1--50},
  volume = {1},
  maintitle = {Psalms},
  series = {Anchor Bible},
  shortseries = {AB},
  number = {16},
  location = {Garden City, NY},
  publisher = {Doubleday},
  date = {1965}
}
@commentary{dahood:1968,
  editor = {Dahood, Mitchell},% note difference in long citation
  title = {Psalms II: 51--100},
  shorttitle = {Psalms II: 51--100},
  volume = {2},
  maintitle = {Psalms},
  series = {Anchor Bible},
  shortseries = {AB},
  number = {17},
  location = {Garden City, NY},
  publisher = {Doubleday},
  date = {1968}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\null\vfill
Permissible options for \texttt{ibidtracker} and \texttt{idemtracker} are
\texttt{true}, \texttt{false}, \texttt{context}, \texttt{strict},
\texttt{constrict}. You might want to play around with them to see what gives
you suitable outcomes. It's unlikely you will want to use \texttt{true} or
\texttt{strict}, since these options do not track things separately in body
and footnotes. \texttt{constrict} is less ambiguous than \texttt{context}.
You must use \texttt{idemtracker=constrict} for the idem behaviour your want.

Filler \autocites{dahood:1965}{dahood:1968}.
Filler \autocites{dahood:1965}{dahood:1968}.
Filler \autocite{dahood:1965}.
Filler \autocite{dahood:1965}.
Filler.\footnote{Filler.}
Filler \autocites(See)(){dahood:1965}{dahood:1965}.
Filler.\footnote{See \cite{dahood:1965}; \cite{dahood:1965}}
Filler \autocite{dahood:1965}.
Filler \autocites{dahood:1965}{dahood:1968}.
Filler \autocite{dahood:1968}.
Filler \autocites{dahood:1965}{dahood:1968}.
Filler \autocite{dahood:1965}.
Filler \parencites{dahood:1965}{dahood:1968}.
Filler \parencite{dahood:1968}.
Filler \autocite{dahood:1968}.

\printbiblist{abbreviations}

\printbibliography

\end{document}
```

**Comment by Nhapsie** [comment]
compiling mwe is a problem still, because of this: `.../idem.tex:37 File `\jobname.bib` not found. \addbibresource{\jobname.bib}`. But I was able use de dev version, and idem was implemented successfully. I added this to my cls: 
`\RequirePackage[citepages=permit,maxbibnames=3,style=sbl,backend=biber,sorting=anyt,fullbibrefs,idemtracker=constrict,ibidtracker=context,pagetracker,ibidpage]{biblatex} `

**Comment by dcpurton** [comment]
you can put the move the filecontents out of the main file and put it in `idem.bib` then use `\addbibresource{idem.bib}` If your editor still can't handle the filecontents package.

I still need to update documentation on this.

**Comment by Nhapsie** [comment]
right, should have thought of that

**Comment by dcpurton** [comment]
I think there's no need to add particular documentation for `\footnote`. It doesn't do anything surprising or different from a normal LaTeX document. I'll just add a not the `\autocite` is placed in parentheses when used in a footnote. (This is what the standard verbose styles do.)

**Comment by Nhapsie** [comment]
Beginners don't know how to insert footnote content that does not include citation. If they need to comment something without actually citing they won't know how to do it.

**Comment by dcpurton** [comment]
Nah - footnotes are standard LaTeX. I can't document every little thing in LaTeX (that would take a very fat book!). It only makes sense to document the specifics of the style. And even then, only where the style departs from standard `biblatex` styles, which already has an extensive manual.

**Comment by Nhapsie** [comment]
No problem, just thought that detail was important due to repetitive use.
