### ISSUE TITLE
bibnamedash wrong for (at least edited) titles and repeated incorrect bibliography entry

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/biblatex-sbl#29]
The following entry appears twice in the bibliography of the test file and is formatted incorrectly the second time (namedashrule needs a comma after it). Not sure if these issues are related or not yet.

> Pritchard, James B., ed. *Ancient Near Eastern Texts Relating to the Old Testament.* 3rd ed. Princeton: Princeton University Press, 1969.

**Comment by Nhapsie** [comment]
Correct, bibnamedash is not active for edited titles, good catch. The output here is this: 

> Pritchard, James B., ed. Ancient Near Eastern Texts Relating to the Old Testament. 3rd ed. ANET. Princeton, NJ: Princeton University Press, 1968.

I think namedashrule uses a period, not comma.

**Comment by dcpurton** [comment]
It did work at one stage.

Should be

———., ed. 

I think.

I'm pretty certain that the doubling of this particular entry is a recent regression too.

**Comment by Nhapsie** [comment]
that could be the case if the second title has editor, but I've always disregarded the "ed" after namedashrule, at least for my university. Well, both options would work for me, but this is less important than getting the rule back. I'm using version from January 18, so probably the error crept in before this date.

**Comment by dcpurton** [comment]
18 Jan! You should use the latest dev version. Lots of problems have been fixed since then.

You need the ed  separate because you could conceivably have two titles with the first one authored and the second one edited by the same person.

Anyway. I'll look into it. Probably in a couple of weeks time.

**Comment by Nhapsie** [comment]
I'm quite positive I used updates after that, don't know why the computer gives that creation date. I see the point, but for us here bibnamedash refers to name only, whether the person is author or editor. I don't recall finding this difference in the SBLHS.

**Comment by dcpurton** [comment]
Ha! The bibnamedash does work. The "———. Ed" output is due to a quirk of the test file, which won't appear in normal usage.

**Comment by dcpurton** [comment]
And I see why the entry is repeated in the bibliography. It's actually in the bib file twice... Once under `ANET` (§6.4.1.2) and once under `pritchard:1969` (§6.2.16). This might have to be manually fudged in the test file so that `pritchard:1969` is suppressed in the bibliography.

**Comment by Nhapsie** [comment]
Have the latest version now, but second instance still has author name rather than bibnamedash.

**Comment by dcpurton** [comment]
Test file should be all fixed in dev version.
