### ISSUE TITLE
Make sblfootnotes option compatible with the footmisc passage

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/biblatex-sbl#30]
It would be useful if the style checks if `footmisc` is loaded and provides that same hooks to easily format indent and justification, and separation of footnotes.

**Comment by Nhapsie** [comment]
Sounds interesting, so how would it work for those who use cls already.

**Comment by dcpurton** [comment]
Won't make any difference. It will just simplify setting up footnotes if you want. I am working on a test file which shows how to implement the SBL example paper given in the student supplement. It will show this kind of thing.

**Comment by dcpurton** [comment]
should work at least at a basic level in dev version

**Comment by Nhapsie** [comment]
good idea!
