### ISSUE TITLE
Widow and Orphan control

### ISSUE THREAD

**Issue by Nhapsie** [dcpurton/biblatex-sbl#33]
I was wondering if there's a way to adjust that. In my case, I need half a line minimum of content, for both footnotes and text. I note that for footnotes at least the default control is off.

**Comment by dcpurton** [comment]
adjusting the length of the final line automatically in LaTeX is not so easy. And this is not a feature that belongs in biblatex-sbl.

Try these options:
http://tex.stackexchange.com/questions/114940/is-there-a-way-to-avoid-short-lines
http://tex.stackexchange.com/questions/63762/minimum-length-of-last-line-of-a-paragraph
http://tex.stackexchange.com/questions/28357/ensure-minimal-length-of-last-line

**Comment by Nhapsie** [comment]
I see. In general, it does not belong natively to LaTeX either, more to desktop publishing apps like InDesign. But the links help, thanks.
