### ISSUE TITLE
use of incollection

### ISSUE THREAD

**Issue by Nhapsie** [dcpurton/biblatex-sbl#35]
This question has to do with clarity in the way we categorize entry types, not how it compiles. In the test file, I notice that `incollection` is used for single works, not collections per se. Examples:

6.2.12 article in edited volume
6.2.13 article in a festschrift 

To cite a chapter from these single works one would think `inbook` fits better than `incollection`. At stake is just the descriptor, for they carry the same format anyway. I would then use `incollection` for actual collections such as in 6.2.22 and 6.2.23. Yes, one can do that already, but I think it would look proper or accurate in the biblatex-sbl.pdf file.

**Comment by dcpurton** [comment]
The difference between a `@book` and a `@collection` is that a `@book` has an author(s) and a `@collection` has contributions from many authors with an overall editor(s).

§6.2.12 and §6.2.13 seem to fall into the category of having many self-contained articles by different authors in a volume with an overall editor. Is this right? If so, I think `@incollection` is more suitable.

I would use `@inbook` for a chapter within a `@book` where the whole book is by the same person as the chapter.

Although by my own logic §6.4.9.1 is wrong...

Have a look at pages 8 and 9 in the `biblatex` manual to see how the various book and collection entry types are defined.

**Comment by Nhapsie** [comment]
Biblatex goes by the criteria of author, whether the same or many. SBL are categorized by types, and there are many types of article chapters. This makes `incollection` appear non-intuitive at times.

**Comment by dcpurton** [comment]
How are you defining a collection as opposed to a single work?

**Comment by Nhapsie** [comment]
A collection is a set of books defined by a series, not a set of chapters in a book.

**Comment by Nhapsie** [comment]
The problem is that now the test files have 5 uses for `incollection` whereas only 1 example for `inbook`. Nothing wrong with that in itself. But for beginners this is confusing, even for me a little. I don't think a change would go against the grain of biblatex, because for the developers they are not steeped into reference types as SBL is. Otherwise they would go by the criterion of book type, not author.

**Comment by dcpurton** [comment]
Ah - I understand where you're coming from. For books in a set `biblatex` would just use `@book` for one volume in an authored `@mvbook`. (Or the analogous `@collection` for one volume in an edited set described by `@mvcollection`.) It's not inconsistent, just different to what you are thinking. e.g., consider this for using the book variants (if it was later republished in one volume, I could use `@bookinbook` instead of `@book` to cite a particular volume):

```TeX
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@mvbook{gonzalez:1987,
  author = {González, Justo L.},
  title = {A History of Christian Thought},
  shorttitle = {History of Christian Thought},
  edition = {rev.\@ ed.},
  volumes = {3},
  location = {Nashville},
  publisher = {Abingdon},
  date = {1987}
}
@book{gonzalez:1987:1,
  crossref = {gonzalez:1987},
  title = {From the Beginnings to the Council of Chalcedon},
  volume = {1}
}
@book{gonzalez:1987:2,
  crossref = {gonzalez:1987},
  title = {From Augustine to the Eve of the Reformation},
  volume = {2}
}
@book{gonzalez:1987:3,
  crossref = {gonzalez:1987},
  title = {From the Protestant Reformation to the Twentieth Century},
  volume = {3}
}
@inbook{gonzalez:1987:1:2,
  crossref = {gonzalez:1987:1},
  title = {The Cradle of Christianity},
  chapter = {2},% Not supported by biblatex-sbl
  pages = {29-60}
}
@suppbook{gonzalez:1987:1:foreword,
  crossref = {gonzalez:1987:1},
  author = {Bainton, Roland H.},
  type = {foreword},
  pages = {13-16}
}
\end{filecontents}
\usepackage[style=sbl,backend=biber]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\strut\vfill
\autocite{gonzalez:1987}
\autocite{gonzalez:1987:1}
\autocite{gonzalez:1987:2}
\autocite{gonzalez:1987:3}
\autocite{gonzalez:1987:1:2}
\autocite{gonzalez:1987:1:foreword}
\printbibliography
\end{document}
```

I'll give it some thought, but on the whole I'm inclined to give examples and especially documentation which is consistent with the standard `biblatex` styles. (And I remain convinced that most people who use this will have had previous exposure to LaTeX, even if you optimistically hope otherwise!)

**Comment by Nhapsie** [comment]
I see what you mean. Thanks.
