### ISSUE TITLE
Heads up: Major breakage with any type using sblxref

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/biblatex-sbl#36]
It turns out that the next version of `biblatex` (3.4) is possibly going to break every type that uses `sblxref` :(.

I will need to look at redesigning how these work. It will mean making `biblatex` 3.4 a minimum requirement and a change in the bib database format.

**Comment by Nhapsie** [comment]
It woul be best to keep the master as stable version 3.3. Dev version could try new solution.

**Comment by dcpurton** [comment]
Yes, I'll make an `experimental` branch and work off that.

I've merged the current `dev` branch into `master` and made a new release (v0.6)

This release works perfectly in `biblatex` 3.1 and 3.2. There is a `biber` bug in `biblatex` 3.3 affecting a less commonly used feature (entries containing both a `shorthand` and a `shortseries`). This release also works with `biblatex` 3.4 up until commit https://github.com/plk/biblatex/commit/1b40caaeae061ae0242315132e6015358c7d3102

It's likely that `sblxref` will be replaced with `xref` along with one or more of `related`, `relatedtype`, and `relatedoptions` fields.

At present there is a bug in `biblatex` that means the `skipbib` option can not be combined with `related` entries, so I won't do anything until this is sorted out.

You can track the conversation at https://github.com/plk/biblatex/issues/407

**Comment by Nhapsie** [comment]
Timely conversation with @plk, thanks. I think it's proper to enter into dialogue with him because `biblatex-sbl` is actively maintained. I think there's a place for innovation and improvement, but backward compatibility is also critical. In other words, they shoud not deprecate elements that quick. I will keep using `biblatex` 3.2 for now.

**Comment by plk** [comment]
This should be the last of such issues I hope - we are in the middle of reconstructing the internals for future expansion and will be more careful about breaking changes. It has brought all sorts of peculiar use-cases out of the woodwork, exposed some bugs and forced some decisions. Painful but not entirely unuseful.

**Comment by dcpurton** [comment]
To be fair to @plk, the way I was doing this was a hack. Hopefully we will end up with the features in biblatex that make what is needed for the SBL style supported without resorting to undocumented and unsupported methods.

**Comment by plk** [comment]
I intend to look at this today and tomorrow and should have a fix soon. I first have to put in some tests for this and some other similar things to prevent regressions.

**Comment by Nhapsie** [comment]
@plk, I was not expecting to get a direct response from you, so thank you for coming and welcome to `biblatex-sbl`. I agree that it's for the best, and trust the three of you in further developing `biblatex` package: by the way there's a lot of people that appreciate you and the team taking over the work begun by Philip Lehman; I am one of them.

**Comment by dcpurton** [comment]
fixed in v0.7
