### ISSUE TITLE
sbl-paper adjustments

### ISSUE THREAD

**Issue by spencerclrk** [dcpurton/biblatex-sbl#39]
- [ ] Remove dots on \subsection and \subsubsection
  - `{\hspace{.5em}\titlerule*[.5pc]{.}\contentspage}` ⟶ 
  - `{\hspace{.5em}\titlerule*[.5pc]{}\contentspage}`

- [ ] Space between \section, \chapter and body text needs to be .25in less.
  - `\titlespacing*{\chapter}{0pt}{29pt}{29pt}` ⟶ 
  - `\titlespacing*{\section}{0pt}{29pt}{12pt}`
  - Issue is that changing this for `\chapter` impacts Bibliography and Appendix differently.

- [ ] Appendix title needs an extra line between `APPENDIX 1` and `APPENDIX TITLE`

> APPENDIX 1
>  
> APPENDIX TITLE

**Comment by dcpurton** [comment]
Point 1: Will do!

Point 2: I think this might be to do with double spacing. I'll look into it.

Point 3: I think this has changed with the second edition of the student supplement. Can you please check in with https://www.sbl-site.org/assets/pdfs/pubs/SBLHSsupp2015-02.pdf

There is also an inconsistency with the numbering of appendices. The exmaple TOC has "Appendix 1: …", which the actual heading has "Appendix 1. …" I opted for the colon, since it looks nicer (IMHO).

**Comment by SClarkWT** [comment]
on pt. 2 it looks like the new student supplement has changed the spacing. So ignore my above comment. The spacing between \section and paragraph text has increased. I'm checking the spacing and will get back to you after I tweak the values.

on pt. 3 you're right. I hadn't updated my example file.

**Comment by SClarkWT** [comment]
This fixes it to the new distance before the headings
`\titlespacing*{\subsection}{0pt}{38pt}{0pt}`

The catch is, the double-spacing is not exactly identical with Word. So, the LaTeX is more spaced out than their example. If you change the double-spacing we will need to update the pt distance before the headings.

**Comment by dcpurton** [comment]
@SClarkWT, if you get a chance, can you please try and figure out what value of `\setstretch` gives the same line spacing as Word double spacing?

**Comment by dcpurton** [comment]
never mind, it looks like `\doublespacing` is correct. For some reason, I had thought this was wrong.

**Comment by dcpurton** [comment]
Check the latest dev branch for improved spacing. How's that look?

**Comment by SClarkWT** [comment]
Looks good from what I can tell. Thanks for your work.
