### ISSUE TITLE
Most types from section 6.4.1 to 6.4.8 (except 6.4.7) are not yet supported

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/biblatex-sbl#4]
This is nearly complete. Just needs some tidying up. Not yet in github

**Comment by dcpurton** [comment]
Done! It would be great if others can help check this:

* check that there are no regressions
* check that the entry structure is sensible (I have no ideas about most of these resources)

Discuss issues and problems in this issue.

**Comment by Nhapsie** [comment]
great job, David! I hope to be able to test it on my day off.

**Comment by baem2** [comment]
I did not check everything, but I played around a bit with it, and it seems good!
