### ISSUE TITLE
Article in single volume dictionary

### ISSUE THREAD

**Issue by Nhapsie** [dcpurton/biblatex-sbl#40]
SBLHS 6.3.6 shows only examples of multi-volume dictionaries, the same goes for the supplement in 1.4. It would be useful to include an example of an entry in, say, DOTP or any other single volume dictionary. I am using `mvcollection` and `incollection` in conjunction and it appears to be working right, but it would be nice to include an example in `biblatex-sbl-test`

**Comment by dcpurton** [comment]
If you want to be consistent, use `collection` instead of `mvcollection`, since you don't have a multi-volume collection.

**Comment by Nhapsie** [comment]
ok thanks

**Comment by Nhapsie** [comment]
there is a problem: `collection` and `incollection` does not yield the format needed for single dictionary entry. Plus it does not inherit the LOA (for those who don't know what this is, list of abbreviations)

**Comment by dcpurton** [comment]
Wait... This is for a dictionary, right? No wonder `*collection` doesn't work. You need to use `mvreference`, `reference`, and `inreference`.

**Comment by dcpurton** [comment]
Do it exactly like §6.3.6, except drop out any volume related field. Can you send me your DOTP example? I'll double check it too.

**Comment by dcpurton** [comment]
I see your point. Punctuation is wrong in Bibliography. But I wonder if it should *always* be the long form (as produced by the `fullbibrefs` package option).

What do you think?

**Comment by Nhapsie** [comment]
(meant to say `inreference` in the first post) Now, `reference` would make sense since it's a single volume dictionary, but there is no use of it in the `biblatex-sbl-test`. The DTOP examples for footnote and bibliography compile right, but no ouput in loa
<img width="331" alt="screen shot 2016-04-21 at 7 24 06 am" 
src="https://cloud.githubusercontent.com/assets/5918656/14708720/47f35872-0792-11e6-992b-e7cfaf84289e.png">
<img width="664" alt="screen shot 2016-04-21 at 7 23 40 am" src="https://cloud.githubusercontent.com/assets/5918656/14708725/4db1e616-0792-11e6-879a-5a140251ef6a.png">

**Comment by dcpurton** [comment]
Try the latest dev branch with this. This now functions the same as single volume commentaries, which I think is the way to go.

```
@reference{DOTP,
  editor = {Alexander, T. Desmond and Baker, David W.},
  title = {Dictionary of the Old Testament: Pentateuch},
  shorttitle = {DOTP},
  location = {Downers Grove, IL},
  publisher = {InterVarsity},
  date = {2003},
  shorthand = {DOTP}
}
@inreference{olson:2003,
  author = {Olson, Dennis T.},
  title = {Numbers, Book of},
  shorttitle = {Numbers},
  pages = {611-618},
  crossref = {DOTP},
  sblxref = {DOTP}
}
```

**Comment by dcpurton** [comment]
I'll add this example to the test file, since I think this is sufficiently different to warrant it.

**Comment by Nhapsie** [comment]
Thanks @dcpurton. The world is a better place now.

**Comment by dcpurton** [comment]
I've added the example to the test file in the dev branch

**Comment by Nhapsie** [comment]
great!
