### ISSUE TITLE
Period issues in `sblpaper`

### ISSUE THREAD

**Issue by spencerclrk** [dcpurton/biblatex-sbl#44]
There's some issues with period placement. Look at the footnotes and places where I cited _Dialogue_.

[Justin Sample.pdf](https://github.com/dcpurton/biblatex-sbl/files/341680/Justin.Sample.pdf)

**Comment by dcpurton** [comment]
Can you post a MWE too please?

**Comment by spencerclrk** [comment]
[mwe.txt](https://github.com/dcpurton/biblatex-sbl/files/342396/mwe.txt)

**Comment by dcpurton** [comment]
Interesting. It's to do with `polyglossia` and Hebrew.

This is enough is exhibit the problem:

```TeX
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{english}
\setotherlanguage{hebrew}
\begin{document}
Hello (\emph{Dial.} 1.4).
\end{document}
```

**Comment by dcpurton** [comment]
I think this is worth asking on tex.stackexchange. I'll post something.

**Comment by dcpurton** [comment]
A work around is to force the numbers to be set left-to-right:

```TeX
(\emph{Dial. \LR{2.1})
```

**Comment by spencerclrk** [comment]
That makes sense. R-L text will sometimes jumble characters if it's in close proximity, but there wasn't any here so I was a tad baffled.

**Comment by dcpurton** [comment]
Try now. I added a fix from http://tex.stackexchange.com/questions/312874/polyglossia-or-bidi-bug-d-gets-inverted-to-d

**Comment by spencerclrk** [comment]
This works, thanks David.
