### ISSUE TITLE
Support all default biblatex fields for supported entry types

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/biblatex-sbl#45]
Many fields from the default biblatex entry types are note supported or incorrectly printed.

**Comment by Nhapsie** [comment]
Elaborate a little on this please.

**Comment by dcpurton** [comment]
This won't affect any standard usage of the style. But at present many fields specified in the biblatex manual for each type are not supported at all and in some cases they cause strange output if they appear in your bib database entry.

I wan't to support them so that a database can be portable across different styles. I'm just using chicago style where the SBL manual lacks info or there isn't any info.

It's also been useful because it has picked up a few bugs as I've gone through this process of adding support for these fields.

**Comment by Nhapsie** [comment]
Oh, nice to know. Thanks for the great support!

**Comment by dcpurton** [comment]
Fixed in v0.8.1
