### ISSUE TITLE
Feature Request: Footnote size and spacing

### ISSUE THREAD

**Issue by folofjc** [dcpurton/biblatex-sbl#51]
The SBL style guide gives a bit of freedom to the size of footnotes. The default in `biblatex-sbl` is 10 point. However, some journals that use the SBL guide specify that footnotes should be 12 point font just like the main body. For example, [Journal of Biblical Literature](https://jbl.scholasticahq.com/for-authors), see Section 2.2. 

It would be great to add an option to the package to set the font size for footnotes, as well as double spacing the footnotes (as in the above JBL requirements).

**Comment by dcpurton** [comment]
LaTeX supports this out of the box, just add `\renewcommand{\footnotesize}{\normalsize}` to your preamble. `sbl-paper.sty` does not do very much special to default footnote settings except the following:

```TeX
\usepackage[bottom]{footmisc}% provides commands below
\renewcommand\footnoterule{\kern-3pt \hrule width 2in \kern 2.6pt\vskip -8pt}% 2in line
\renewcommand\footnotelayout{\raggedright}% ragged right
\setlength{\footnotemargin}{0.5in}% right indent
\setlength{\footnotesep}{18pt}% right separation from text
```

Is this good enough?

**Comment by folofjc** [comment]
That is what I am doing to solve it, and it works for a paper I am working on right now. I have noticed in the past, however, working with other packages that messing around with `footnotesize` can have some unintended consequences when other people use that (as is also noted in the answer [here](https://tex.stackexchange.com/questions/46197/want-to-change-footnote-size-for-biblatex-chicago-citations). I wasn't sure if it would mess other things up, especially with the use of polyglossia, etc. If that is all it takes, then that works for me! I just wanted to be sure, thanks for the help!

**Comment by dcpurton** [comment]
Ah. Yes, you are right. That stack exchange answer is better. I'll think about it.

**Comment by folofjc** [comment]
I agree that the fix in #49 fixes #48 as well. However, since I am trying to format in JBL style (as discussed here), I was using this bug as an "undocumented feature" to get double spaced footnotes. Is there any easy way to add that capability? Seems to me like having the option for both (with single space as the default) would be an ideal solution. Thanks!

**Comment by dcpurton** [comment]
Untested, but does `\renewcommand{\footnotelayout}{\doublespacing}` space the footnotes correctly?

**Comment by dcpurton** [comment]
It seems like it would be useful to be able to pass a style option to `sbl-paper.sty` to specify student style or jbl style, etc. For simple style differences this shouldn't be too hard. But I'm not sure if it's worth trying to support many different styles in what is meant to be basically just an example.

**Comment by folofjc** [comment]
Yeah, I wasn't thinking a whole bunch of different styles. I was merely thinking that since the SBLHS leaves a couple options open, and since the JBL (published by same organization that came up with SBLHS and SBLHS Student Supplement) does something different than the student supplement, it might be good to allow for these differences. Any other changes to SBLHS that other people make, I agree that it should be up to the user. 

I really need to get better at pure TeX so I can know how to do some of this myself. Thanks for all your help! I'll try the above in a little bit.

**Comment by folofjc** [comment]
The above does indeed appear to work. I left in the `maketitle` command, and added the above in the preamble. Looks okay to me at first glance. Thanks!

**Comment by folofjc** [comment]
One more question/comment about `sbl-paper.tex`. Your example uses the `book` class, but this doesn't have an option for an abstract. Have you tested with the `article` class? Any thoughts on whether `sbl-paper.sty` would or wouldn't work with a different class?

**Comment by dcpurton** [comment]
Actually, I think I should just re-implement the whole thing as a class based on `memoir` which allows for much easier tweaking of just about everything.

Maybe I could make it a separate package.

In answer to you `book` question, it should work with `article` class just fine.

**Comment by dcpurton** [comment]
Ha! It's way easier in `memoir`. I should have used that to start with. It shouldn't take too long to have a style that supports a student style and a JBL style. Even and SBL book style will be easy enough.

**Comment by folofjc** [comment]
Awesome! Sounds great. Looking forward to it!

**Comment by jackweinbender** [comment]
I'm working on a semi-modular dissertation class, based on `memoir`, too.
