### ISSUE TITLE
Behaviour of particles in names

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/biblatex-sbl#53]
Following on from discussions in #52, I think it's worth discussing how names with particles should be handled.

For background, see *SBLHS,* §7.2.2.

This is from page 114 (2nd edition):

> A particle in a given person’s name should have the same case in running text, footnotes,
> bibliographies, and indexes whether or not the surname is preceded by a first name or
> initials. Thus:
>
> > In his earlier works, Gerhard von Rad said . . .
> > In his earlier works, von Rad said . . .
> > In his earlier works, François Du Bois said . . .
> > In his earlier works, Du Bois said . . .
>
> Any name with a particle at the beginning of a sentence is capitalized:
>
> > Von Rad often said . . .

And this is from page 115, which is to be used for indexes and alphabetisation.

> Rad, Gerhard von
> Van Seters, John

And from page 17 of the student supplement:

> Rad, Gerhard von. *Genesis: A Commentary.* Translated by John H. Marks. OTL. Philadelphia: Westminster, 1990.

And from page 87 of *SBLHS*:

> 17. Van Seters, “Theology of the Yahwist,” 222.
>
> Van Seters, John. “The Theology of the Yahwist: A Preliminary Sketch.” Pages 219–28 in *“Wer ist wie du, Herr, unter den Göttern?”: Studien zur Theologie und Religionsgeschichte Israels für Otto Kaiser zum 70. Geburtstag.* Edited by Ingo Kottsieper et al. Göttingen: Vandenhoeck & Ruprecht, 1995.

So does this mean the `\citeauthor` and `\textcite` should always behave as if the option `useprefix=true`, but in the index and bibliography it should behave as if the option `useprefix=false`? What about subsequent citations with `\autocite`? e.g., What about something like a reference to von Rad's commentary on Genesis. Should it be:

> 2. Rad, *Genesis,* 10. (current behaviour)

or

> 2. Von Rad, *Genesis,* 10.

At present `biblatex-sbl` leaves `useprefix=false` in both citations and bibliography unless explicitly set to `true` in the bib entry. This matches the behaviour of `biblatex-chicago`.

I'd be interested to hear people's opinion on this. @lyndondrake, @Nhapsie, @folofjc, @jackweinbender, @baem2, @spencerclrk

**Comment by lyndondrake** [comment]
Well, in my view the first option (current behaviour) is more consistent with the style guide, because then the footnote text matches the listing in the bibliography. I *like* the second option better, but that's because I disagree with the style guide

**Comment by jackweinbender** [comment]
I haven't had the opportunity to look at the Handbook myself, but assuming your examples are correct, I think the current behavior is in line with the style guide.

**Comment by folofjc** [comment]
Maybe I am missing something, why is Van Seters capitalized and von Rad not in the handbook on pg 115, and likewise on 87? Does it depend on how the author chooses to capitalize their name? It seems to me that if you wanted Van Seters to be capitalized, you would just put the "Van" in the last name field of the bib entry, and if you didn't you would put it in the particle portion in the bibliography entry. Therefore you could leave the package behavior the same and let the user decide where to put it in the bib entry. Or am I way off base?

On a side note, I have two friends who are brothers that have a "van" in their name. They admit that they are not consistent either as a family or as individuals. Sometimes they capitalize, sometimes not. Sometimes they even remove the space between the "van" and the last name portion.

**Comment by jackweinbender** [comment]
I think the handbook treats them differently based on how the author treats it? For Van Seters, they're treating his last name as "Van Seters" while for von Rad, his surname is "Rad." I guess it's analogous to the distinction between Karel van der Toorn and James VanderKam.

**Comment by Nhapsie** [comment]
On page 114 of the SBLHS 2.0 manual, Van Seters is capitalized and alphabetized because of it’s Americanized version of the German. So for the German scholar von Rad, only “Rad” gets alphabetized.

**Comment by dcpurton** [comment]
@folofjc, yes the case of Van Seters is not a problem. `biblatex` automatically assumes it is part of the family name when it is capitalised in the bib entry (e.g., `author = {Van Seters, John}`). To be considered as a prefix, the bib entry must have the particle in lowercase (e.g., `author = {von Rad, Gerhard}`).

I just included it above for the sake of comparison.

**Comment by folofjc** [comment]
Got it. I say leave behavior as it is, like everyone else recommended.
