### ISSUE TITLE
Upcoming changes in biblatex 3.8: origlanguage becomes a list

### ISSUE THREAD

**Issue by moewew** [dcpurton/biblatex-sbl#57]
In the upcoming (and as of now unreleased) version 3.8 of `biblatex` `origlanguage` will change its type from `field` to `list`.

A short grep of installed `biblatex` styles showed that your style might be affected.
https://github.com/dcpurton/biblatex-sbl/blob/1dd58592c12fdef8e00197f304d0405f4d6e81b8/latex/biblatex-sbl.def#L888-L906

For background info see https://github.com/plk/biblatex/issues/594

You might also want to have a look at the other changes in 3.8 https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org

**Comment by dcpurton** [comment]
Fixed in commit 49285e2604a999f44d0cb6f8939b91e70f793848
