### ISSUE TITLE
\citeshorthand error 

### ISSUE THREAD

**Issue by Nhapsie** [dcpurton/biblatex-sbl#58]
Biber (2.6 with BibLaTeX 3.5) produces a warning for `\citeshorthand` "SBL" within the example `@conferencepaper{niditch:1994,` from `biblatex-sbl-test` (page 36 of version Jan 11, 2017). There is no "SBL" output in the List of Abbreviation, at least on my end. I'm using the latest master files.

**Comment by dcpurton** [comment]
I can't reproduce this.

Can you post the output when you run `pdflatex` on this MWE:

```TeX
\listfiles
\documentclass{article}
\usepackage[style=sbl]{biblatex}
\addbibresource{biblatex-sbl.bib}
\begin{document}
\cite{niditch:1994}
\printbiblist{abbreviations}
\printbibliography
\end{document}
```

Don't forget you will need to run `pdflatex`, `biber`, `pdflatex`, `biber`, `pdflatex` to get the final output because of the cite within the cite.

**Comment by Nhapsie** [comment]
Thank you, it worked. As an aside, I'm missing the total range of pages for Niditch in your example on page 36.

**Comment by dcpurton** [comment]
Hi @Nhapsie, can I check what you mean here? There is no `pages` field in the `niditch`, so no total page range is printed. This matches the handbook, and I wouldn't expect a total page range to be given for an unpublished conference paper.

And what do you mean by *use of pagination*?

**Comment by Nhapsie** [comment]
Thanks for your reply, all is well. I had to remove `pages = ...` from my `bib` file as @conferencepaper does not take pages. Makes sense because it is unpublished.
