### ISSUE TITLE
spacing regression in list of abbreviations in biblatex-sbl 0.9

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/biblatex-sbl#66]
I missed a couple of % signs :( leading to extra leading spaces in the list of abbreviations.

**Comment by dcpurton** [comment]
I'll leave it a few more days before doing a CTAN update in case other problems are found :(

**Comment by Nhapsie** [comment]
I noticed that a few hours ago, great catch.

**Comment by Nhapsie** [comment]
Maybe it would be a good idea to inform CTAN users of our Git link. Or maybe not.
