### ISSUE TITLE
6.2.25 Electronic Book (optional fields)

### ISSUE THREAD

**Issue by Nhapsie** [dcpurton/biblatex-sbl#67]
The SBL Handbook of Style has reduced bibliographic data for the Reventlow example. I'm sending a link of the first pages of this work for verification. The missing fields in the manual are: series, and number. The printed counterpart could be either 6.2.21 or 6.2.22 depending on how one wants to cite this reference. 

[Pages from Reventlow2009 - From the Old Testament to Origen.pdf](https://github.com/dcpurton/biblatex-sbl/files/2023766/Pages.from.Reventlow2009.-.From.the.Old.Testament.to.Origen.pdf)

```
@book{reventlow:2009,
  author = {Reventlow, Henning Graf},
  title = {From the Old Testament to Origen},
  volume = {1},
  series = {Resources for Biblical Study},
  shortseries= {RBS},
  number = {50},
  maintitle = {History of Biblical Interpretation},
  translator = {Perdue, Leo G.},
  location = {Atlanta},
  publisher = {Society of Biblical Literature},
  date = {2009},
  eprint = {Nook},
  eprinttype = {ebook}
}
```

![screen shot 2018-05-21 at 3 18 14 pm](https://user-images.githubusercontent.com/5918656/40327960-5655de1a-5d0a-11e8-9978-ca0fe346b142.jpg)

**Comment by dcpurton** [comment]
This isn't actually a problem with output though, right? You get what you want if you add in the fields?

I don't think this is a bug and I'm not worried that the Handbook doesn't always include all fields. You only really have to include enough information to find the resource in your bibliography.

**Comment by Nhapsie** [comment]
understood
