### ISSUE TITLE
Abbreviation absent in LOA (6.2.5 SBLHS 2.0)

### ISSUE THREAD

**Issue by Nhapsie** [dcpurton/biblatex-sbl#70]
Hello @dcpurton, I noticed today that the abbreviation`shortseries` is missing on the list of abbreviation for an original work (or any other?) included in reference type `6.2.5 The Full History of a Translated Volume` The abbreviation comes out good for footnote and bibliography though.

**Comment by dcpurton** [comment]
Hi @Nhapsie, as usual, please *always* include a minimal working example, even if you think things are clear.

**Comment by Nhapsie** [comment]
The `MWE`
```

\documentclass[a4paper]{article}
\raggedright
\usepackage[style=sbl,ibidtracker=false,backend=biber]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{Gluck1927,
author = {Glück, Nelson},
title = {Das Wort \emph{Ḥesed} Im Alttestamentlichen Sprachgebrauch Als Menschliche und Göttliche Gemeinschaftgemäße Verhaltungsweise},
shorttitle = {Das Wort \emph{Ḥesed} Im Alttestamentlichen Sprachgebrauch},
series = {Beihefte zur Zeitschrift für die alttestamentliche Wissenschaft},
shortseries = {BZAW},
number = {47},
publisher = {Alfred Töpelmann},
location = {Gießen, Germany},
date = {1927},}

@book{Gluck1967,
author = {Glück, Nelson},
title = {Hesed in the Bible},
translator = {Gottschalk, Alfred},
location = {Cincinnati, OH},
publisher = {Hebrew Union College Press},
related = {Gluck1927},
relatedtype = {translationof},
date = {1967},}

@book{Gluck2011,
author = {Glück, Nelson},
editor = {Epstein, Elias L.},
title = {\emph{Ḥesed} in the Bible},
translator = {Gottschalk, Alfred},
location = {Eugene, OR},
publisher = {Wipf \& Stock},
related = {Gluck1967},
relatedtype = {reprintof},
date = {2011},}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Example: \cite[101]{Gluck2011}.
\printbiblist{abbreviations}
\printbibliography
\end{document}
```

**Comment by dcpurton** [comment]
This happens because `biblatex` excludes `related` entries from both the bibliography and the LOA.

The solution is to add `relatedoptions={skipbib}` to the `Gluck1967` entry. This will ensure that `Gluck1927` is not included in the bibliography, but is included in the LOA.

I think I might be able to do this be default without side effects (I basically do this for `@ancienttext` and `@classictext` entry types already.)

(BTW, you get get your German accents showing up by adding `\usepackage{fontspec}` to your MWE and compiling with `xelatex` or `lualatex`.)

**Comment by dcpurton** [comment]
@Nhapsie, see if the latest git version of the master branch does what you want and expect.

**Comment by dcpurton** [comment]
I think the issue is valid. It's unexpected for all `shortseries` to be included in the LOA except for ones in `related` entries.

I don't remember this being mentioned before. You can search github issues on the main issues page.

**Comment by Nhapsie** [comment]
Thanks for the change, now `related` deploys `shortseries` in LOA right out of the box
