### ISSUE TITLE
Title only partly in italics

### ISSUE THREAD

**Issue by Nhapsie** [dcpurton/biblatex-sbl#71]
Consider this title in my bib file as a book title: `title = {Wellhausen's \textit{Prolegomena to the History of Israel:} Influences and Effects}.` The macro will place the whole thing in italics. But the original includes part of it in italics, which must be turned off for emphasis when the macro deploys. How to do this?

**Comment by Nhapsie** [comment]
It appears I'm doing it wrong. It should be `\emph` as in `title = {Wellhausen's \emph{Prolegomena to the History of Israel:}`

**Comment by dcpurton** [comment]
Yes, `\textit` *always* uses italics. `\emph` switches around based on context. I've noticed in some cases `\mkbibemph` is a little smarter with `biblatex`. But you should be fine with plain old `\emph`.
