### ISSUE TITLE
Support for asterisked (`\cite*{}) commands

### ISSUE THREAD

**Issue by jackweinbender** [dcpurton/biblatex-sbl#74]
Perhaps there is a more idiomatic method within `biblatex-sbl`, but I'm looking for a way to suppress the author when using the `\cite...` command. I know standard `biblatex` styles use `\cite*{...}`, but that doesn't seem to work here.

**Comment by dcpurton** [comment]
I've followed the default `verbose` styles which do not support \cite* (and relatives). I notice there is a workaround at https://tex.stackexchange.com/a/262472/87678.

I'm not sure why the default `verbose` style don't support this, but I can't see why I couldn't add this feature.

**Comment by jackweinbender** [comment]
Great. FWIW, the specific use case I'm dealing with is using `\cite*` in footnotes where I've already mentioned the author's name.

**Comment by dcpurton** [comment]
@jackweinbender , can you check if the latest commit does what you want?

**Comment by jackweinbender** [comment]
I haven't tried it with every entry type, but, as far as I can tell, this is spot-on. Thanks! 

One of these days I'm going to actually learn some TeX and contribute back to this project. Your work has been immensely helpful for me over the years (back to pre-biblatex days!).
