### ISSUE TITLE
Mainauthor documentation

### ISSUE THREAD

**Issue by spencerclrk** [dcpurton/biblatex-sbl#75]
A unique use case is Moulton's *Grammar*. It has four volumes, but some of them are written by other authors — but the main work is still attributed to Moulton.

From [SBLHS2.com](https://sblhs2.com/2017/04/20/citing-reference-works-7-greek-language-tools/)
> 56. Nigel Turner, *Style*, vol. 4 of *A Grammar of New Testament Greek*, by James Hope Moulton, 4 vols. (Edinburgh: T&T Clark, 1908–1976), 71.

I discovered that using `mainauthor` does indeed produce the desired result, but this is not documented in the `biblatex-sbl.pdf`.

Result:
> 168. Nigel Turner, *Syntax*, vol. 3 of *A Grammar of New Testament Greek*, by James Hope Moulton, 4 vols. (Edinburgh: T & T Clark, 1908-1976).

Source:
```latex
@mvbook{Turner:1963aa,
	Author = {Nigel Turner},
	Location = {Edinburgh},
	Mainauthor = {James Hope Moulton},
	Maintitle = {A Grammar of New Testament Greek},
	Publisher = {T \& T Clark},
	Title = {Syntax},
	Volume = {3},
	Volumes = {4},
	Year = {1908-1976}}
```

**Comment by dcpurton** [comment]
Thanks! I must have forgotten to put it in. Also, I didn't know about that website either. I might take a closer look.
