### ISSUE TITLE
No longer use ibid by default

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/biblatex-sbl#76]
In line with the 17th edition of the Chicago Manual of Style, SBL no longer prefers to use ibid (and presumably idem).

See https://sblhs2.com/2018/02/01/cms-update-ibid/

So these features should be turned off by default.

(They will still be supported.)

**Comment by Nhapsie** [comment]
Thanks for the information. It's always a good thing to simplify things, so I think they're on the right track
