### ISSUE TITLE
No page numbers for first citation of incollections

### ISSUE THREAD

**Issue by baem2** [dcpurton/biblatex-sbl#8]
If you're quoting specific pages of a INCOLLECTION entry in the first quote (where you have the full quote), the given pages just disappear: It only shows the pages where you can find the whole essay in the book, but not the pages you're actually quoting.

The same happens with ARTICLEs.

MWE:

```
\listfiles
\documentclass{article}
\usepackage[english]{babel}

\usepackage[utf8]{inputenc}

\begin{filecontents}{test.bib}
@incollection{attridge:1986,
	author = {Attridge, Harold W.},
	title = {Jewish Historiography},
	pages = {311-343},
	booktitle = {Early Judaism and Its Modern Interpreters},
	editor = {Kraft, Robert A. and Nickelsburg, George W. E.},
	publisher = {Philadelphia: Fortress; Atlanta: Scholars Press},
	date = {1986}
}
\end{filecontents}

\usepackage[style=sbl]{biblatex}
\bibliography{test.bib}

\begin{document}
A short test: \cite[312--314]{attridge:1986}
And now it works: \cite[313--315]{attridge:1986}
\end{document} 
```

**Comment by baem2** [comment]
And after some more tests: This probably happens for everything that uses a 'pages' entry. I can confirm it for INCOLLECTION, INBOOK, and ARTICLE.

**Comment by Nhapsie** [comment]
Hi Phillip

What David and I designed is for first quote of chapter to output total pagination automatically. If you need to cite pages in addition to that use prenote, and your specific pages will be output in parenthesis. If you need a mwe let me know and I will send one that David produced. 

Carlos

**Comment by baem2** [comment]
Well, my point is that the specific pages are not there for me. Just check my MWE, I am using the prenote there.

**Comment by Nhapsie** [comment]
> On Jan 15, 2016, at 12:50 PM, Philipp <notifications@github.com> wrote:
> 
> Well, my point is that the specific pages are not there for me. Just check my MWE, I am using the prenote there.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/dcpurton/biblatex-sbl/issues/8#issuecomment-172050226>.
> 
can’t compile yours. Try this: 

\documentclass[a4paper]{article}

\usepackage{fontspec}
\usepackage[citepages=permit,style=sbl,backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@suppbook{boers:1996,
  author = {Boers, Hendrikus},
  type = {introduction},
  booktitle = {How to Read the New Testament: An Introduction to Linguistic and Historical-Critical Methodology},
  bookauthor = {Egger, Wilhelm},
  translator = {Heinegg, Peter},
  location = {Peabody, MA},
  publisher = {Hendrickson},
  date = {1996},
  pages = {i-xii}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}

\autocite{boers:1996}
\citereset
\autocite[ii]{boers:1996}
\citereset
\autocite[a note]{boers:1996}
\autocite{boers:1996}
\autocite[iii]{boers:1996}
\autocite[iii]{boers:1996}
\autocite[a note]{boers:1996}

\printbibliography

\end{document}

**Comment by Nhapsie** [comment]
Can't compile your MWE. Try this

[code]
\documentclass[a4paper]{article}

\usepackage{fontspec}
\usepackage[citepages=permit,style=sbl,backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@suppbook{boers:1996,
  author = {Boers, Hendrikus},
  type = {introduction},
  booktitle = {How to Read the New Testament: An Introduction to Linguistic and Historical-Critical Methodology},
  bookauthor = {Egger, Wilhelm},
  translator = {Heinegg, Peter},
  location = {Peabody, MA},
  publisher = {Hendrickson},
  date = {1996},
  pages = {i-xii}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}

\autocite{boers:1996}
\citereset
\autocite[ii]{boers:1996}
\citereset
\autocite[a note]{boers:1996}
\autocite{boers:1996}
\autocite[iii]{boers:1996}
\autocite[iii]{boers:1996}
\autocite[a note]{boers:1996}

\printbibliography

\end{document}
[/code]

**Comment by baem2** [comment]
Ah, okay, ``citepages=permit`` does the trick! Thanks! That solves the problem!

(The biblatex-dw package I am using usually does this automatically, it seems ...)

**Comment by Nhapsie** [comment]
how do you enclose coding to appear in gray here?

**Comment by baem2** [comment]
Am 15.01.2016 um 20:17 schrieb Nhapsie:
>
> how do you enclose coding to appear in gray here?
>
For a full block three times ` before and after the block, for some words two times `.

**Comment by Nhapsie** [comment]
Oh, thank you!

**Comment by dcpurton** [comment]
Further to comments by Carlos:

In line with the standard styles, there are a number of options possible for `citepages`.

* `citepages=sbl` (default). Uses full pages in first citation no matter what. This is what most examples in the handbook do.
* `citepages=permit`. Includes the specified page in parentheses after the full page reference for the first citation.
* `citepages=omit`. Only includes the full page reference if no specific page is specified.
* `citepages=separate`. Gives this behaviour: 45–48 (esp. 46). Especially is provided y the bibliography string `thiscite` which may be redefined.

The standard styles also support `citepages=suppress`, but I have just removed this option because it gave ambiguous results when the postnote format was `volume:pages`.

**Comment by baem2** [comment]
Ooh, good to know, thanks. ``citepages=separate`` is what exactly fits my needs!
