### ISSUE TITLE
Multi-part article

### ISSUE THREAD

**Issue by jackweinbender** [dcpurton/biblatex-sbl#92]
As always, thanks for keeping up with this project.

I'm interested in what the proper way is (if, indeed there is) to encode a multi-part article in a journal.

I'm citing August Dillmann's "Das Buch der Jubiläen oder die kleine Genesis" which was published in two parts (and, with identical titles) in successive volumes of *Jahrbücher der Biblischen Wissenschaft* (2 [1849] and 3 [1850--51]). To be completely honest, I don't even really know what it should ultimately look like, and I may still be better off just citing them separately for specific references, but I'm not sure about the bibliography (maybe best to just cite them separately, too).

In at least one location I've seen this:
```
Dillmann, August "Das Buch der Jubiläen oder die kleine Genesis." JBW 2 (1849): 230--56; 
      3 (1851): 1--96.
```

Any thoughts?

Edit: I've confirmed the above to be the correct way to format the citation according to SBLHS2 (p. 92)

**Comment by dcpurton** [comment]
You can see how I did this in §6.3.2 of `biblatex-sbl-examples.pdf`.

It's not pretty, but I can't see another way of doing it. Also it's not completely fool proof as it gives wrong output for short citations when no `postnote` is given.

(Actually I'm not super sure what *should* happen when you cite a work with `pages` in its `bib` entry with no `postnote` in short citations. At present I put in the value of `pages`. I do this on the basis of entry types which are like "`volume`:`postnote`". It looks odd to finish a citation with "`volume`:" so I opted to put in the `pages` field.)

The problems from upstream `biblatex` are:
- `date` can have a date range, but not a list of dates.
- `pages` isn't a list either.

So you have to implement some kind of hack.

I'm open to better ideas.

# MWE

```TeX
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{Dillman18491851,
  author = {Dillmann, August},
  title = {Das Buch der Jubiläen oder die kleine Genesis},
  journaltitle = {Jahrbücher der biblischen Wissenschaft},
  shortjournal = {JBW},
  pages = {2 \mkbibparens{1849}: 230--56; 3 \mkbibparens{1851}: 1--96}
}
\end{filecontents}
\usepackage[style=sbl,ibidtracker=false,idemtracker=false]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\null\vfill
Filler text \autocite{Dillman18491851}.

\textbf{Question: Is this the right form?}
Filler text \autocite[230]{Dillman18491851}.
Filler text \autocite[1]{Dillman18491851}.

\textbf{But this is wrong:}
Filler text \autocite{Dillman18491851}.
\printbiblist{abbreviations}
\printbibliography
\end{document}
```

![output](https://user-images.githubusercontent.com/6268044/51226018-577ed300-199d-11e9-90e6-da06f65c9a9c.png)

**Comment by jackweinbender** [comment]
My instinct is to agree with your approach here. My hack was basically the same as yours (using the `page` field). I threw that entry in a `nocite` and I added individual `bib` entries for each part so I could cite them separately, (and adding `skipbib`).

The catch here is that the first instance of each "part" citation gets a full-note and obviously things like `Ibid.` won't play nice.

I found [this stackoverflow thread](https://tex.stackexchange.com/questions/187807/biblatex-cite-an-article-published-in-several-installments-multiple-years-and) which basically comes to the same conclusions we have. Perhaps you will get something out of it that I didn't.

**Comment by moewew** [comment]
The `related` function could be an obvious choice to try and implement this, but depending on the exact wishes for the output it might still be complicated.

Most fields involved aren't lists and even if they were lists (leaving aside the issue of how one could turn `pages` into a list properly) they would probably have to be printed interleaved as in `<vol_1>: pages_1, <vol_2>: pages_2, ..., <vol_n>: pages_n`, which makes things even more complicated (I have never tackled this interleaved list printing, but I seem to remember some contributed `biblatex` style that does it in another situation, maybe it is `biblatex-sbl`).

With `related` we can at least handle each 'subpart' of the article properly and try to combine it into a larger one. See for example https://github.com/plk/biblatex/issues/272 from which I shameless copied the idea and code for my answer to https://tex.stackexchange.com/q/232526/35864.

**Comment by dcpurton** [comment]
Using `related` looks like it will work really well! Thanks @moewew!

Advantages of the MWE example below:
- Can easily cite either just one of the individual articles or the combined article
- No `volume`/`date`/`page` hacks.

Current problems:
- `\relateddelimmultivolarticle` doesn't work. I can't work out why yet, but it seems to fail for the `biblatex` standard styles too, so perhaps its a `biblatex` bug. I'll do some more testing.

```TeX
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{Dillman18491851,
  author = {Dillmann, August},
  title = {Das Buch der Jubiläen oder die kleine Genesis},
  journaltitle = {Jahrbücher der biblischen Wissenschaft},
  shortjournal = {JBW},
  related = {Dillman1849,Dillman1851},
  relatedtype = {multivolarticle}
}
@article{Dillman1849,
  crossref = {Dillman18491851},
  volume = {2},
  date = {1849},
  pages = {230-256}
}
@article{Dillman1851,
  crossref = {Dillman18491851},
  volume = {3},
  date = {1851},
  pages = {1-96}
}
\end{filecontents}
\usepackage[style=sbl,ibidtracker=false,idemtracker=false]{biblatex}
\addbibresource{\jobname.bib}
\newbibmacro*{related:multivolarticle}[1]{%
  \entrydata*{#1}{%
    \printfield{volume}%
    \setunit*{\addperiod}%
    \printfield{number}%
    \setunit{\addcomma\space}%
    \printfield{eid}%
    \usebibmacro{issue+date}%
    \usebibmacro{pages}}}
\newcommand*{\relateddelimmultivolarticle}{++\addsemicolon\space}
\newcommand*{\begrelateddelimmultivolarticle}{\addspace}
\begin{document}
\null\vfill
Filler text \autocite{Dillman18491851}.
Filler text \autocite[230]{Dillman18491851}.
Filler text \autocite[1]{Dillman18491851}.
Filler text \autocite{Dillman18491851}.
\printbiblist{abbreviations}
\printbibliography
\end{document}
```

![output](https://user-images.githubusercontent.com/6268044/51251531-7905ac00-19e9-11e9-9653-27c315aa2f29.png)

**Comment by dcpurton** [comment]
@moewew , your fix seems to work fine for this MWE.

I would *never* have even understood enough to get to putting in all those `\expandafter` commands. In fact I'm pretty weak on anything that requires more that *one* `\expandafter`...

Thanks!

**Comment by dcpurton** [comment]
As a note, more code is needed to actually provide a robust solution. Fields that come after the `pages` field need to be handled and also different options of `citepages` should be checked.
