### ISSUE TITLE
Sorting Bibliography Entries

### ISSUE THREAD

**Issue by jackweinbender** [dcpurton/biblatex-sbl#95]
Although it is not explicitly stated in SBLHS2 (as far as I've been able to find), I think bibliography entries by the same author should be sorted by title, *but should ignore forms of the article*. This is based on the CMS, admittedly (16, 17, and 18 are all the same).

Or should this be dealt with in the `.bib` file (using `sorttitle` or the like)?

**Comment by dcpurton** [comment]
Sorry for the late reply!

I haven't done this automatically. But yes, you can control this with `sorttitle`.

It could be done automatically with a source map fairly easily though.

**Comment by Nhapsie** [comment]
I have been sorting by publication date

**Comment by dcpurton** [comment]
@Nhapsie, Can we try and find source for what is the right solution. The default `biblatex` sorting option is `nty` for Name, Title, Year. And I have not changed that in `biblatex-sbl`. This makes sense to me as the order of fields in the bibliography is name, title, year. I would typically use name, year, title for and author year citation style. Either way, changing `sorttitle` as this commit does won't affect your sorting scheme, unless you have two entries with same author and same year. Then the title will be considered minus any article.

**Comment by Nhapsie** [comment]
I found nothing of the "sort" in the SBLHS 2. That is, version 2 is silent on bibliography sorting. My institution allows me to sort Author-Date-Title, so I have been using it. But I asked the staff of the SBLHS on the matter and here is their response: 

"Although there is technically no right or wrong on how to arrange a bibliography, every publisher or professor I know will expect a traditional bibliography to be arranged by author and title. Thus, multiple works by the same author will be arranged alphabetically by title. The SBLHS does not address this explicitly (we likely will in the next edition), deferring for the moment to the Chicago Manual of Style, 17th edition,  §§14.65-71"

**Comment by dcpurton** [comment]
Thanks @Nhapsie
